### ISSUE TITLE
How to add shortcode with js?

### ISSUE THREAD

**Issue by BerenChang** [hugo-toha/toha#1014]
### Question
I am adding a word counter as a shortcode and use it in a post. Not sure if I've done right because apparently js did not work. I did the following:

1. Fork this repo.
2. Add wordcounter.js to /static/js
3. Add wordcounter.html to /layouts/shortcodes
4. Use the forked repo as hugo theme
5. Use {{< wordcounter >}} as the shortcode command

But apparently the wordcounter textarea box showed up but it was not counting. Where have I done wrong?

wordcounter.js:
https://github.com/BerenChang/toha/blob/main/static/js/wordcounter.js

wordcounter.html:
https://github.com/BerenChang/toha/blob/main/layouts/shortcodes/wordcounter.html

**Comment by hossainemruz** [comment]
Btw, Hugo has buit-in method for word counting. You don't need to implement on your own.
https://gohugo.io/methods/page/wordcount/
