### ISSUE TITLE
Accessibility and SEO

### ISSUE THREAD

**Issue by alex-bezek** [hugo-toha/toha#111]
I would like to increase the google lighthouse scores of Accessibility and SEO
Example scores from my home page:
![image](https://user-images.githubusercontent.com/8029578/96658148-d42ca700-1311-11eb-8dba-8a7459c25a5a.png)
![image](https://user-images.githubusercontent.com/8029578/96658166-db53b500-1311-11eb-8cf5-7a0a34e8ab2d.png)

I took an initial stab at updating the home page and was able to get this
![image](https://user-images.githubusercontent.com/8029578/96658328-3685a780-1312-11eb-9a6b-19685d5c99a5.png)

The remaining issue is a contrast issue between the light blue text in many places so I didn't want to change your design.
I have a work in progress branch here https://github.com/hossainemruz/toha/compare/master...alex-bezek:accessability-seo?expand=1
You can see the visual diffs in my percy build https://percy.io/alex-bezek/blog/builds/7376731?utm_campaign=alex-bezek&utm_content=blog&utm_source=github_status_public . 

If this change looks good, I'll go ahead and clean it up and finish doing the posts list and single views and open a PR

**Comment by hossainemruz** [comment]
Accessibility and SEO scores are now much better in the latest version. Still, we will like to improve. We will be tracking this topic in this new issue:
https://github.com/hugo-toha/toha/issues/838
