### ISSUE TITLE
Error building site: Failed to get JSON resource

### ISSUE THREAD

**Issue by sarru1291** [hugo-toha/toha#122]
While setting up Toha for local development, I encountered this error and failed to build a site.
The local development guide also seems a little confusing, which I'll myself update later.

<img width="565" alt="Screenshot 2020-10-24 at 10 18 21 PM" src="https://user-images.githubusercontent.com/22962336/97087500-4cfc6d80-1648-11eb-8b07-d1fe39bbcf1c.png">

**Comment by hossainemruz** [comment]
What is your hugo version?

**Comment by alex-bezek** [comment]
FWIW I get this too, I'm on 0.72.0. In my PR to the example site, i actually removed it temporarily
https://github.com/hossainemruz/toha-example-site/pull/13#discussion_r511461774

It seems instagram is deprecating their api, so I'm not sure the long term plan.

**Comment by sarru1291** [comment]
> What is your hugo version?

Earlier I'd 0.71. But now as I've upgraded to the latest 0.76.5, I'm still getting the same error.

**Comment by alex-bezek** [comment]
@sarru1291  with the latest push here https://github.com/hossainemruz/toha-example-site/commit/a86fa0c8280ecf6f54cd39b707ec7804ba3b8cd3#diff-f1d4f8b8885304eb0466e24713c05fb216518485caeea85d4f22c214b740fdb4 the build should be fixed if you want to verify

> The local development guide also seems a little confusing, which I'll myself update later.

Do you still plan on making an update or would you be able to explain what is confusing? I'd be happy to update it with your feedback if you don't have time

**Comment by sarru1291** [comment]
Thanks, it's working now.
