### ISSUE TITLE
Scroll-spy not working on top navbar

### ISSUE THREAD

**Issue by hossainemruz** [hugo-toha/toha#132]
## Expected Behavior

![image](https://user-images.githubusercontent.com/12577390/97740720-e5449780-1b0b-11eb-821e-f277372893cb.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/12577390/97740631-c2b27e80-1b0b-11eb-9c7f-c96f67f955e4.png)

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by alex-bezek** [comment]
@hossainemruz I reverted my commit here https://github.com/hossainemruz/toha/commit/c85bcf8488754677329a4b2b556eb51e11959af0#diff-557ff321de56eb6c5c6f40beb6c6cb3105adacc4deaa15db2448a168d12d82a7 and it fixed this issue (but reintroduces the previous issue). I'll look into this more

**Comment by alex-bezek** [comment]
@hossainemruz opened a PR here https://github.com/hossainemruz/toha/pull/138/files
