### ISSUE TITLE
Achievements Mobile Popup issue

### ISSUE THREAD

**Issue by alex-bezek** [hugo-toha/toha#137]
## Expected Behavior
The achievements Section when clicked expands to show its full content and can then be closed after.

## Current Behavior
On mobile devices it does this, then disappears and none of the sections are accessible

## Possible Solution
I haven't looked into it yet, I'll update this when i get a chance

## Steps to Reproduce

1. Click on a specific achievement item using mobile on android or IOS
2. Once it opens wait
3. See that it closes and no other items are accessible

### Screenshots
<img src="https://user-images.githubusercontent.com/8029578/97768044-ba9c1400-1af6-11eb-9650-ecb25cd46723.png" width="200" />
<img src="https://user-images.githubusercontent.com/8029578/97768053-c556a900-1af6-11eb-88ea-3b96a9616fe5.png" width="200" />
<img src="https://user-images.githubusercontent.com/8029578/97768062-cd164d80-1af6-11eb-8827-691df1bf3a5f.png" width="200" />

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
- [x] Mobile Chrome
- [x] Mobile Safari

**Comment by hossainemruz** [comment]
I can confirm this weird behavior. Not sure why it is happening.

**Comment by RunesReader** [comment]
I confirm this bug.

**Comment by hossainemruz** [comment]
This should be fixed in the latest version of the theme. Try updating the theme version. Feel free to re-open if the issue still persist.
