### ISSUE TITLE
Header menu gets completely highlighted after scrolling

### ISSUE THREAD

**Issue by ipankajsingh** [hugo-toha/toha#144]
## Expected Behavior
When we scroll, the menu shouldn't get highlighted on it's own unless we select a particular section from the menu or only the section selected from the menu should be highlighted.

## Current Behavior
1. Scrolling  a little highlights the entire menu.
2. Selecting any section scrolls the blog to that section but again highlights the entire menu instead of a particular section.
3. Scrolling all the way up doesn't restores the transparent menu background and the background remains white.

## Steps to Reproduce

1. Go to https://toha.netlify.app/
2. Select any section from the menu or scroll manually to see the entire menu getting highlighted 
3. Scroll back to home and see that the menu is still having white background.

### Screenshots

After scrolling to top, the menu remains white
![image](https://user-images.githubusercontent.com/24999656/97797742-85520c00-1c45-11eb-93db-04a7e7041309.png)

After scrolling down, the entire menu is highlighted.
![image](https://user-images.githubusercontent.com/24999656/97797751-969b1880-1c45-11eb-83a5-9949ef3d82da.png)

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge

**Comment by hossainemruz** [comment]
@ipankajsingh This has been fixed in #138. Try pulling the latest master.

**Comment by hossainemruz** [comment]
Feel free to reopen if you still face the issue after updating the theme to latest version.
