### ISSUE TITLE
Selecting sections from header menu but lands at different positions.

### ISSUE THREAD

**Issue by iPankajKumar** [hugo-toha/toha#154]
## Expected Behavior
The position should be fixed for the start of every section, whenever we select any section from header menu.

## Current Behavior
When we select Experience section, it goes to a position and then shifts up, some times it doesn't (which is correct.) 

## Steps to Reproduce

1. Select Experience section and notice the scroll, it goes to the correct position and shifts up.
2. Try randomly scrolling and going back to Experience section, sometimes it goes to the right position , sometimes it shifts up.

Have a look in the  gap between menu & Experience title.

### Screenshots

Correct position. (Correct gap between menu and Title)

![image](https://user-images.githubusercontent.com/24999656/98020676-4f6d7d00-1e29-11eb-8ceb-62cc765bff9b.png)

Wrong position. (After the section shifts up, the gap between menu and Title reduces)

![image](https://user-images.githubusercontent.com/24999656/98020720-657b3d80-1e29-11eb-922a-030b22e84434.png)

### Browsers Affected

- [ x] Chrome

- [x ] Edge
 &  All chromium based browser.

**Comment by hossainemruz** [comment]
I can confirm the behavior. I will try to fix ASAP.

**Comment by ipankajsingh** [comment]
@hossainemruz 
Any update on this ?

**Comment by hossainemruz** [comment]
Sorry, I haven't been able to look at it.
