### ISSUE TITLE
theme update failed

### ISSUE THREAD

**Issue by serverfriendsorg** [hugo-toha/toha#162]
## Expected Behavior
I expect that hugo starts the webserver and loads the page.

## Current Behavior

Error: Error building site: failed to render pages: render of "home" failed: "/home/serverfriendsorg/projects/mygit.com/serverfriendsorg/themes/toha/layouts/index.html:53:18": execute of template failed: template: index.html:53:18: executing "index.html" at <partial (printf "sections/%s.html" (replace (lower .section.id) " " "-")) .>: error calling partial: partial "sections/.html" not found
`

## Steps to Reproduce
1. cd themes/toha
2. git submodule update --remote --merge
3. hugo server -w

**Comment by hossainemruz** [comment]
Now, you have to provide `id` for your sections. Please follow the following format: https://github.com/hugo-toha/hugo-toha.github.io/blob/4fccce7b5756c333f619eebc1c16b2ed61e6e3c3/data/en/sections/projects.yaml#L4

**Comment by serverfriendsorg** [comment]
> Now, you have to provide `id` for your sections. Please follow the following format: https://github.com/hugo-toha/hugo-toha.github.io/blob/4fccce7b5756c333f619eebc1c16b2ed61e6e3c3/data/en/sections/projects.yaml#L4

Thanks it's working now.
