### ISSUE TITLE
Use Hugo's Image Processing

### ISSUE THREAD

**Issue by patmagauran** [hugo-toha/toha#171]
The theme should use [Hugo's built in image processing](https://gohugo.io/content-management/image-processing/) throughout the project, both in the posts as well as the main page layout. I think this can be done through a global resource and the appropriate functions.

**Comment by RotatingFans** [comment]
I did a test with the Avatar image on the home page and was able to get it to work, so it shouldn't be too hard to do. I will try to get a pull request together soon. However, it will require moving the images from the static folder to the assets folder. So we will need to update the docs as well.

**Comment by hossainemruz** [comment]
>However, it will require moving the images from the static folder to the assets folder.

Probably this was the reason why I didn't use Hugo's native image processing. Is there any other possible issues that may cause by moving the images outside of the static folder? Obviously, it's going to be a breaking change.

**Comment by RotatingFans** [comment]
I am not deeply familiar with Hugo, but overall the change seems pretty painless. No changes are needed to the configuration, just copy the images folder from /static to /assets. Obviously this is a breaking change, so it would be important to determine a way to override this. Perhaps a configure option: useImageProcessing, that will allow for the images to be pulled from the asset folder, which would be false be default when upgrading.

**Comment by hossainemruz** [comment]
Done in #173
