### ISSUE TITLE
Font doesn't support Cyrillic

### ISSUE THREAD

**Issue by driukova** [hugo-toha/toha#174]
I really like your theme, it's just the best. However, I've faced difficulties in localizing site to Russian as the font used in the theme doesn't support Cyrillic. 
I'll create a pull request with ru.toml on this weekend so that can be tested and hopefully fixed. Thanks in advance!

**Comment by driukova** [comment]
Added a PR with ru.toml #175

**Comment by hossainemruz** [comment]
Fixed in #175
