### ISSUE TITLE
Skill Summary Breaking for line more than 2

### ISSUE THREAD

**Issue by JOSHUAJEBARAJ** [hugo-toha/toha#179]
## Expected Behavior
Skill Summary should be aligned and displayed without no white spaces

## Current Behavior
Skill Summary Displaying with the white spaces

## Steps to Reproduce

1.Create the simple hugo website using **tugo** theme
2.Copy and paste the skills summary with more than two line

```
Capable of Writing program using the following Languages Java,Bash,Python,Golang.
```

### Screenshots
<img width="1412" alt="Screenshot 2020-12-03 at 6 03 02 AM" src="https://user-images.githubusercontent.com/19353065/100948665-67224900-352e-11eb-97a4-3a6ab8a5a5bd.png">

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 11
- [ ] Safari 10
- [ ] IE 11

[Github-Link](https://github.com/JOSHUAJEBARAJ/my-website)
[Website-Link](https://www.joshuajebaraj.com/)

**Comment by hossainemruz** [comment]
The behavior is expected. Card texts are justified. It is by design.
