### ISSUE TITLE
bug in footer.html

### ISSUE THREAD

**Issue by dyingway** [hugo-toha/toha#183]
## Expected Behavior

themes\toha\layouts\partials\footer.html
Navigation can't show the right url

such as (https://toha-guides.netlify.app/posts/#about)

## Possible Solution

line 33:
`<a class="smooth-scroll" href="{{ "#" | absURL }}#{{ $sectionID }}">{{ .section.name }}</a>`
## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ 1] Chrome
- [ ] Firefox
- [ 1] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Thank you @dyingway for reporting.

**Comment by jeffkeller87** [comment]
Undoing #95 fixed this for me.

**Comment by hossainemruz** [comment]
Already fixed in `main` branch.
