### ISSUE TITLE
"Improve this page" defaults to master branch

### ISSUE THREAD

**Issue by MarionMoseby** [hugo-toha/toha#184]
## Expected Behavior
When I click "Improve this page", it should load the main branch, as currently master is being phased out due to racist implications

## Current Behavior
It loads the repo's main branch

## Possible Solution
Make it configurable. Also, I would love to see an "Improve this website" button on the main page, not just the blog, to highlight it is OSS

## Steps to Reproduce
Click on "Improve this Page" on any toha website

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by hossainemruz** [comment]
Thank you @MarionMoseby for reporting. I will try to fix it ASAP.

**Comment by hossainemruz** [comment]
This has been already fixed in `main` branch. We have introduced `gitBranch` options in `params` section of `config.yaml` file.
