### ISSUE TITLE
Why not usde TOML?？ Same as HUGO

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#189]
Why not usde TOML?？ Same as HUGO

**Comment by hossainemruz** [comment]
Because I can only do YAML. :P

**Comment by DarrellDudics** [comment]
I've used this YAML to TOML converter and have taken all of the settings in documentation and converted them to TOML and I have no issues running this theme:

https://www.convertsimple.com/convert-yaml-to-toml/

**Comment by Chow-Ray** [comment]
@DarrellDudics thanks！
