### ISSUE TITLE
How to insert a link to new tab?

### ISSUE THREAD

**Issue by rever96** [hugo-toha/toha#192]
I'm trying to insert a link to my post that open url in a new tab

- `[This]("https://www.google.com")`
- `<a src="https://www.google.com" target="_blank"> This </a>`
- `{{<a src="https://www.google.com" target="_blank"> This </a>}}`

Nothing of these works good.
What's the soloution?

**Comment by hossainemruz** [comment]
This should work
```html
<a href="http://example.com/" target="_blank">Hello, world!</a>
```
