### ISSUE TITLE
Template issue post theme update

### ISSUE THREAD

**Issue by darkwizard242** [hugo-toha/toha#205]
## Expected Behavior
Successful hugo build.

## Current Behavior

```shell
render of "section" failed: execute of template failed: template: _default/list.html:6:8: executing "_default/list.html" at <partial "header.html" .>: error calling partial: "mysite/themes/toha/layouts/partials/header.html:11:31": execute of template failed: template: partials/header.html:11:31: executing "partials/header.html" at <$favicon.MediaType.SubType>: nil pointer evaluating resource.Resource.MediaType
```

## Steps to Reproduce

1. `git submodule update --remote`
2. `hugo -D --minify `

## Detailed Description

Hugo version: **0.80.0**

I was previously on commit hash: `203380f121944c26a8c66f994c459287e16cb6e9` for toha theme as a submodule for site project.

After updating today, I seem to be getting the error mentioned in **Current Behavior**.

Not sure if I am missing something, but would certainly appreciate some help.

**Comment by hossainemruz** [comment]
Put your logos in `/assets/images` folder of your repository.

**Comment by darkwizard242** [comment]
Thank  you @hossainemruz , that did the trick 👍🏻  I did get another error for partials/helpers/get-author-image.html, partials/sections/home.html - but figured that was due to not having moved author image as well.

Is it safe to consider that the images for skills/projects/achievements etc.. can remain in `static/images/sections/{projects,achievements,skills}` as I did not see any [documentation](https://toha-guides.netlify.app/posts/getting-started/prepare-site/) update for those?

**Comment by darkwizard242** [comment]
Actually I guess they also needed moving since I tested out by moving them to `assets/images/sections/{projects,achievements,skills}` , which worked out except for **skills** for some reason.

**Comment by hossainemruz** [comment]
All images should now go to `/assets/images` folder.  I didn't update the docs yet.

**Comment by darkwizard242** [comment]
No worries, it's understandable as I am sure you have a day job too 😄 thanks anyways 👍🏻

**Comment by harsh-kotak** [comment]
> Actually I guess they also needed moving since I tested out by moving them to `assets/images/sections/{projects,achievements,skills}` , which worked out except for **skills** for some reason.

I have the same issue. Moved all images to assets but images in skills section do not work. I did not find the img-src in rendered HTML for skills.

**Comment by ngoldack** [comment]
I'm having the same issue.

**Comment by hossainemruz** [comment]
@darkwizard242 , @harsh-kotak , @ngoldack are you guys still facing the issue? Try updating the theme to `v2.0.0`. Move all images into `assets` directory from `static`.

**Comment by darkwizard242** [comment]
@hossainemruz Yes, the issue for **skills** sections images not rendering still exists.. Also with the latest commit "d5be769", I did notice that images for **posts** don't seem to render either and are being defaulted to the theme's.

![Screenshot from 2021-03-15 11-47-14](https://user-images.githubusercontent.com/40025815/111181385-4d0ff200-8584-11eb-9fbe-477853b4561b.png)

For instance, they originally exist in their relevant folders and were loading fine before: 
<site-git-repo>/content/posts/<category>/<post-dir>/hero.jpg

Other than the above mentioned, I have not seen any other issue.

**Comment by hossainemruz** [comment]
@darkwizard242 can you please point me to your repository.

**Comment by harsh-kotak** [comment]
mine is https://github.com/harsh-kotak/ikotak

**Comment by darkwizard242** [comment]
sure @hossainemruz .. since the repository is private, I added you as a collaborator.

**Comment by hossainemruz** [comment]
@harsh-kotak I don't see any issue with your site. Its building without any error or warning.
![image](https://user-images.githubusercontent.com/12577390/111503443-f74c6d00-8770-11eb-8950-d95f8cb28eed.png)

**Comment by hossainemruz** [comment]
@darkwizard242 I don't see your repo. I haven't received any invitation for collaboration.

**Comment by harsh-kotak** [comment]
> @harsh-kotak I don't see any issue with your site. Its building without any error or warning.
> ![image](https://user-images.githubusercontent.com/12577390/111503443-f74c6d00-8770-11eb-8950-d95f8cb28eed.png)

Never had issue with building site. The images in skills section are not working.

**Comment by darkwizard242** [comment]
@hossainemruz - can you please confirm if you see the invite (spam and other places with the email address associated to your github username)? It does say it's awaiting.. If not, I will do some refactoring and set it to public if needed.

![Screenshot from 2021-03-17 20-27-25](https://user-images.githubusercontent.com/40025815/111555656-38d41c80-875f-11eb-95d5-8d980d788d34.png)

**Comment by hossainemruz** [comment]
@darkwizard242 its rendering fine for me. I don't see any error or warning.
![image](https://user-images.githubusercontent.com/12577390/111571125-6dcc8780-87d0-11eb-9e87-d834348b293c.png)

![image](https://user-images.githubusercontent.com/12577390/111571199-905ea080-87d0-11eb-87a2-bc2f23611f73.png)

What hugo version are you using? Make sure to run `git submodule update` to update the theme.

**Comment by darkwizard242** [comment]
@hossainemruz - thanks for checking up and apologies for the delay in response.

The issue is that both the images in the Skills Section and the Recent Posts section don't seem to be rendering anymore. I did bump the theme to `1c3154d` today as a test, was originally on `d5be769` last time I reported this.. Example screenshots below:

![Screenshot from 2021-03-24 13-26-02](https://user-images.githubusercontent.com/40025815/112372528-4dac3500-8cb6-11eb-944b-b2f7e769b964.png)
![Screenshot from 2021-03-24 13-25-52](https://user-images.githubusercontent.com/40025815/112372530-4dac3500-8cb6-11eb-9afa-ba4aafd5558a.png)

**Comment by hossainemruz** [comment]
@darkwizard242 Sent you an PR with the fix. The problem was followings:
- The hero image path is relative to post folder.
- The `icon` filed in skills section has been renamed to `logo`.

This commit fixes the issues: https://github.com/darkwizard242/alimuhammad-dev/pull/8/commits/186f48788df05aa65e5c10e71307ebd6f01c8fa5

**Comment by darkwizard242** [comment]
@hossainemruz - Really appreciate that, thanks man. PR fixed issue for both skills and recent posts 👍🏻

**Comment by hossainemruz** [comment]
Great to know. Can you please close the issue?

**Comment by darkwizard242** [comment]
Sure 👍🏻 thanks again for your help!
