### ISSUE TITLE
How to modify the transparency of the homepage background? 

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#211]
### Question

Hi，Plz help me. 
How to modify the transparency of the homepage background? 
Only the background of the red marked area becomes opaque
thanks so much！
![无标题](https://user-images.githubusercontent.com/29678677/103636542-18305f00-4f85-11eb-96dc-c422fbdff0f3.png)

**Comment by adarshbm82** [comment]
I did it by changing this 
toha/static/css/navigators.css 

.initial-navbar {
  background-color: #244;
}

**Comment by hossainemruz** [comment]
You don't need to modify theme CSS. Just put your custom CSS into `assets/css/style.css` file of your repository.

**Comment by Chow-Ray** [comment]
> I did it by changing this
> toha/static/css/navigators.css
> 
> .initial-navbar {
> background-color: #244;
> }

thanks so much！

**Comment by Chow-Ray** [comment]
> You don't need to modify theme CSS. Just put your custom CSS into file of your repository.`assets/css/style.css`

But how to make the background picture clear?

**Comment by Chow-Ray** [comment]
ok.I have found a solution。Modify the code`/static/css/sections/home.css`
```
background {
  height: 100%;
  width: 100%;
  padding: 0;
  margin: 0;
  background-attachment: fixed;
  background-position: center;
  transform: scale(1.1);
  /*filter: blur(3px);*/
  background-size: cover;
}
```
