### ISSUE TITLE
toha/exampleSite/data/cn/sections/projects.yaml bug

### ISSUE THREAD

**Issue by dyingway** [hugo-toha/toha#214]
## Expected Behavior

weight:5
## Current Behavior

\data\cn\sections\projects.yaml:7:1": failed to unmarshal YAML: yaml: line 7: could not find expected ':'
## Possible Solution

weight: 5,need space.
## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Thanks for reporting. Should be fixed by #215
