### ISSUE TITLE
Modify header and footer as if they were just another section

### ISSUE THREAD

**Issue by jpmvferreira** [hugo-toha/toha#224]
Being able modify the header and the footer as if they were another section would make it easier to fully customize the website.

For example I would like to keep things as clean as possible and given that I have no intention to translate to other languages having the language on the top right can be misleading. Commenting it out is an option but having the intention to not having the logo on the header and centering the rest of the menu is not an option.

The same thing applies for the footer, allowing the user to customize a set of parameters.

**Comment by Kaligule** [comment]
One great feature here would be to allow to completly disable header and footer. Personally I would like to get rid of the footer entirely for my site.

**Comment by hossainemruz** [comment]
Ok, we can do this. Just need some free time.

**Comment by Kaligule** [comment]
So this might be a stupid question, but is the flag-problem maybe solved already?

The flags are inserted into the navigation bar [here](https://github.com/hugo-toha/toha/blob/v2.2.0/layouts/partials/navigators/navbar.html#L106):

```html
{{ if .IsTranslated }}
  {{ partial "navigators/lang-selector.html" . }}
{{ end }}
```

`IsTranslated` is a variable set by hugo itself.
The [hugo documentation](https://gohugo.io/variables/page/) tells us about it:

```
.IsTranslated
    true if there are translations to display.
```

And indeed, on my site there are no flags to see:

![Screenshot_2021-04-28_13:56:46](https://user-images.githubusercontent.com/3586246/116399820-9f9e2880-a829-11eb-8613-2fbbc4dd0af1.png)

So how do we know if there are translations?
I am not sure, but I guess removing the "langues" section from your site config might do the trick.
@jpmvferreira  Could you give this a try?

**Comment by hossainemruz** [comment]
Made footer configurable in #303 . Thanks to @Kaligule . You can now enable or disable a particular section of the footer. You can even provide a custom footer template.
Example: https://github.com/hugo-toha/hugo-toha.github.io/blob/5fcc45e97514e1c206a91ab1291b0da9d65da758/config.yaml#L69

**Comment by Kaligule** [comment]
@hossainemruz Thank you. I think the navbar (what is probably what @jpmvferreira meant with "header") is not yet configurable, right? So we should either reopen this issue or open a new one.

**Comment by hossainemruz** [comment]
The Navbar is already configurable. User can show/hide a particular section in the navbar
