### ISSUE TITLE
Errors in the Console

### ISSUE THREAD

**Issue by RunesReader** [hugo-toha/toha#239]
## Expected Behavior

When we loading site the console should be without errors
## Current Behavior

When we loading site console has 4 errors
## Possible Solution

Sorry, I am working as iOS Developer :((
## Steps to Reproduce

1. Open, for example [my site](https://arsenkin.name)
2. Observe a console

### Screenshots

![Screenshot 2021-02-24 at 10 22 09](https://user-images.githubusercontent.com/12240504/108971454-fef58600-768a-11eb-962b-d30ddced4e90.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 14

**Comment by hossainemruz** [comment]
The console log looks clean to me.
![screenshot](https://user-images.githubusercontent.com/12577390/108972876-f19dc300-76ad-11eb-9f0f-53838229588f.png)

**Comment by RunesReader** [comment]
Ok! Maybe these are minor errors.
