### ISSUE TITLE
hero bug

### ISSUE THREAD

**Issue by baocaifeng** [hugo-toha/toha#240]
## Expected Behavior

---
In my /posts/test/graphic/index.md
I put all hero images in static folder, I write:
~~~
title: "Graphic"
date: 2021-02-25T21:30:39+01:00
draft: false
description: xxxxxxxxxxxxxx
hero: /img/posts/test/graphic/graphic-hero.png
menu:
  sidebar:
    name: Graphic
    identifier: graphic
    parent: test
    weight: 90
~~~

**The post should use the hero that I customized**

## Current Behavior

but, it's not. **It still uses the default hero**

## Possible Solution

I checked the file partial/helpers/get-hero.html
However, its logic logic looks that it won't check the given path of hero in the post.
It only checks the current folder and the default hero.
However in the doc, it says that we can define our own hero in the post like I did.
To fix it, I need to add some line to make the it check the defined param *hero* in the post.
 
~~~
{{/* check if there is any hero image in the same folder as the markdown file */}}
{{ $heroImage := .Page.Resources.GetMatch "hero.{jpg,png,svg}"}}
{{ .Scratch.Set "heroScratch" $heroImage }}

{{/* if hero image is not provided, then use the default hero image */}}
{{ if not $heroImage }}
  {{ $heroImage := resources.Get "images/posts/default-hero.png"}}
  {{ .Scratch.Set "heroScratch" $heroImage }}
{{ end }}

{{ $heroImage := .Scratch.Get "heroScratch" }}

{{/* resize hero image. don't resize if the image is an svg */}}
{{ if and $heroImage (ne $heroImage.MediaType.SubType "svg") }}
  {{ $heroImage := $heroImage.Resize "148x" }}
{{ end }}

{{/*  return the hero image  */}}
{{ return $heroImage.RelPermalink }}
~~~

**Comment by yeganathan18** [comment]
Hey @baocaifeng 
I'm also getting the same error, I tried implementing your above-mentioned code but seems like the issue still persists.

**Comment by baocaifeng** [comment]
@yeganathan Hey, I have modified the code and it fixed the problem

**Comment by baocaifeng** [comment]
@yeganathan18 maybe this can help you :)

In the post, define a path of hero. Please attention !! put your hero in assetDir. I before made a mistake and put my hero in the staticDir, cause I don't familiar with hugo. In the html code, we use the hugo default function **ressourceGet**, so take care of this !
~~~
---
title: "Graphic"
date: 2021-02-25T21:30:39+01:00
draft: false
description: Graphical Reasoning Test
hero: images/posts/graphic-hero.png
menu:
  sidebar:
    name: Graphic
    identifier: graphic
    parent: test
    weight: 90
---
~~~


in the get-hero.html, change it to:
~~~
{{/* check if there is any hero image in the same folder as the markdown file */}}
{{ $heroImage := .Page.Resources.GetMatch "hero.{jpg,png,svg}"}}
{{ .Scratch.Set "heroScratch" $heroImage }}

{{/* if hero image is not provided, then use the default hero image */}}
{{ if not $heroImage }}
  {{ $heroImage := resources.Get "/images/posts/default-hero.png" }}
  {{ .Scratch.Set "heroScratch" $heroImage }}
{{ end }}

{{/* if hero is provides in assetDir, then use that */}}
{{ if .Params.hero }}
  {{ $heroImage := resources.Get .Params.hero }}
  {{ .Scratch.Set "heroScratch" $heroImage }}
{{ end }}

{{ $heroImage := .Scratch.Get "heroScratch" }}

{{/* resize hero image. don't resize if the image is an svg */}}
{{ if and $heroImage (ne $heroImage.MediaType.SubType "svg") }}
  {{ $heroImage := $heroImage.Resize "148x" }}
{{ end }}

{{/*  return the hero image  */}}
{{ return  $heroImage.RelPermalink }}
~~~~

**Comment by baocaifeng** [comment]
@yeganathan18 hey, I'll close this issues ^^, because I found solutions for my blogs. If you need any help, don't hesitate to ask questions here ! have a good  day

**Comment by yeganathan18** [comment]
Thanks for you help!
Let me try it once again as mentioned above :)

**Comment by ahmadmssm** [comment]
Is there any update on this bug other than the manual solutions that alter the theme code ?

**Comment by yeganathan18** [comment]
@ahmadmssm I don't think so.

**Comment by hossainemruz** [comment]
This should have been fixed in the latest release. The demo site already uses an example of custom hero image.
https://raw.githubusercontent.com/hugo-toha/hugo-toha.github.io/source/content/posts/category/sub-category/rich-content/index.md
