### ISSUE TITLE
What's the best way to center images in Posts with this theme?

### ISSUE THREAD

**Issue by tgreaves** [hugo-toha/toha#241]
### Question
I love the theme! Thanks for all your work on it.

I'm wondering the best way of centering images in Posts.  So far, the best I have is this:

```
{{< img src="/images/posts/my-image.png" align="center">}}
```

This works, but means the images have to live in `static`.  This feels awkward given the main theme images are all in `assets`.

I found the `rimg` shortcode but it doesn't seem to do alignment.  `<figure>` seems to be the sort of thing I need in general, but also isn't centering.

What's the cleanest way of achieving this?

**Comment by tgreaves** [comment]
As an update, `<figure>` alone does center the image, and also puts the nice border around it (great!) -- but is loading from 'static'.  Is this generally the way we shoud be doing things now?  Or is there room for a new shortcode in the theme which loads from `assets` instead?

**Comment by hossainemruz** [comment]
I think we should add a new shortcode for `figure`.

**Comment by hossainemruz** [comment]
@tgreaves `img` shortcode can load image from the post folder. Here, is an example: https://hugo-toha.github.io/posts/shortcodes/
Here is the markdown: https://github.com/hugo-toha/hugo-toha.github.io/blob/source/content/posts/shortcodes/index.md
