### ISSUE TITLE
what is the "maps.Params"

### ISSUE THREAD

**Issue by baocaifeng** [hugo-toha/toha#242]
### Question

Hi ! I found this in file /layout/partials/helpers/get-author-name.html
I don't understand this code, pls help me.
So, the *(printf "%T" .Params.author )* is the *type* of  *.Params.author* ?
what is the *maps.Params* ? I can't find any doc about this in Hugo and I'm not familiar with Go.

And, *why* here do you want to compare the *type* (if I misunderstand, pls tell m) ?
I mean, for me, I will only test if the *.Params.author.name* existes, then return it.
I don't understand the *maps.Params*, and this kind of codes existes in many places, I may miss understand something important. Thank you very much if anyone can help me.
~~~
{{/*  Lastly, overrides with the post specific author if provided  */}}
{{ if eq (printf "%T" .Params.author ) "maps.Params" }}
    {{ with .Params.author }}
        {{ if .name }}
        {{ $authorName = .name }}
        {{ end }}
    {{ end }}
{{ end }}
~~~

**Comment by hossainemruz** [comment]
I really forgot why, I have used that 😄 . Btw, closing this issue.
