### ISSUE TITLE
I am getting an error while changing yaml file

### ISSUE THREAD

**Issue by rshah1990** [hugo-toha/toha#244]
Hi Team,

Thank you for this wonderful theme. I always get below error if I change anything in YAML file.

ExampleSite -> data -> en -> sections -> YAML files

![image](https://user-images.githubusercontent.com/37735152/109507240-85172f80-7ac4-11eb-97bc-b7f1b15cc511.png)

**Comment by stueja** [comment]
Same for me, @rshah1990 . How did you solve that?
