### ISSUE TITLE
Multi language search only works on the sites main language

### ISSUE THREAD

**Issue by MarionMoseby** [hugo-toha/toha#249]
## Expected Behavior
If I search in mysite.me/es/posts, I should get results in spanish

## Current Behavior
I only get results if the word I query is found in mysite.me/posts, and, if the word is in mysite.me/es/posts but not in mysite.me/posts, I get no result

## Possible Solution
I am not really sure, maybe changing index.json to not only include index but also index/languagecode?

## Steps to Reproduce
1. https://hugo-toha.github.io/search/?keyword=intro : Yes results
2. https://hugo-toha.github.io/search/?keyword=%E0%A6%AD%E0%A7%82%E0%A6%AE%E0%A6%BF%E0%A6%95%E0%A6%BE : No results

### Browsers Affected
All

---

Btw just wanted to use this bug report to thank you for the amazing theme! I know search is still in early stages, I just wanted to let you know this

**Comment by hossainemruz** [comment]
That's right. Multi-language hasn't been handled in search yet.  This is initial support for search functionality. It may take some time to implement the multi-language support.
