### ISSUE TITLE
Accomplishment feature available to work on ?

### ISSUE THREAD

**Issue by HenzelMoras** [hugo-toha/toha#259]
### Is someone working on accomplishment feature ?
if not than i would like to add it bc i somwhat implemented it in my site 
![accomplishment](https://user-images.githubusercontent.com/60033549/112211299-b9a08600-8c41-11eb-8298-c2479c113a0d.png)
png)

also what do u mean by overview ?

**Comment by hossainemruz** [comment]
Hi @HenzelMoras it is not done yet. It would be great if you can send a PR.

>also what do u mean by overview ?

A summary of what you did/learn on this course.

**Comment by HenzelMoras** [comment]
Hi @hossainemruz  okay on it.
 i followed readme for contributing 

which folder im supposed to edit   
```
hugo-toha.github.io/themes/toha/{files-to-edit}
```
?

**Comment by hossainemruz** [comment]
Yes.

**Comment by HenzelMoras** [comment]
okay thank you

**Comment by hossainemruz** [comment]
Added on   #262
