### ISSUE TITLE
Icon and line is not showing on Education Section from Mobile

### ISSUE THREAD

**Issue by Nirzak** [hugo-toha/toha#286]
## Expected Behavior

It should show like the following
<img src="https://user-images.githubusercontent.com/11460645/113475312-b0f84d00-9496-11eb-9667-279e4b837c16.jpg" width=50% height=50%>

## Current Behavior

But it is showing like this
<img src="https://user-images.githubusercontent.com/11460645/113475322-bf466900-9496-11eb-8c3a-74e4140e1d1b.jpg" width=50% height=50%>

## Possible Solution

Don't know if it's intentional or not. If not intentionally then removing the following code from education.css file will fix this issue.
`  .education-section .icon {
    display: none;
  }
  .education-section .line {
    display: none;
  }`
### Browsers Affected

- [x] Chrome Mobile
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
This is by design. Mobile has small screen real state. We should prioritize readability and user experience over decoration.

**Comment by Nirzak** [comment]
> This is by design. Mobile has less screen real state. We should prioritize readability and user experience over decoration.

Yeah I also though so. Ok bhai then please close this issue thanks.
