### ISSUE TITLE
Add Contact Form functionality

### ISSUE THREAD

**Issue by daveops1** [hugo-toha/toha#29]
It would be nice to have the option to include a contact form, allowing the form action to be whatever forms provider the user chooses like Netlify, Typeform, etc...

**Comment by hossainemruz** [comment]
Can you please point me to some example for contact form? I have no idea on how they works.

**Comment by daveops1** [comment]
Sure!  I'm actually working on a custom section now using your theme's basic framework.  I can share when I'm finished.  Essentially since Hugo generates a static site, need to have a `<form action=#>` pointing to an API that handles contact form submissions.  Here are some links below that show this idea:

- https://medium.com/getform-all-about/how-to-add-a-contact-form-to-your-hugo-website-84ea79683399
- https://brianli.com/how-to-create-a-contact-form-in-hugo-with-netlify-forms/

**Comment by Nirzak** [comment]
How about an in-built Netlify form to use. But the only drawback will be one must have to use Netlify. This is the major drawback of Hugo, actually. As it's a static site generator, we have to use dynamic servers to handle requests on the static Hugo for many features.

**Comment by Nirzak** [comment]
> Since, the theme now support specifying template for a section, we can definitely have Netlify form as a Contact form template.

Yup netlify has an official documentation for forms. https://docs.netlify.com/forms/setup/ and this post from hugo community can be helpful for the implementation https://discourse.gohugo.io/t/is-it-possible-to-add-a-contact-form-to-a-site/1550/2 I have found a sample code from victor hugo's hugo-cms-template git here https://github.com/netlify-templates/one-click-hugo-cms/blob/master/site/layouts/partials/contact-form.html

**Comment by hossainemruz** [comment]
Ok. I will try to design the form layout whenever get some time.

**Comment by hossainemruz** [comment]
You can add your own contact form following this guideline.
https://toha-guides.netlify.app/posts/customizing/new-section/
