### ISSUE TITLE
Horizontal scroll bar on small devices

### ISSUE THREAD

**Issue by chutified** [hugo-toha/toha#304]
I noticed a vertical scroll bar on smaller screens (width: less than 618px). It is there for an excess white small stripe on the right side. I couldn't exactly find the source of the problem, but it seems to have something to do with the `skills` section because the moment I remove this section in the chrome inspection the horizontal scroll bar disappears and only reappears when the width of the page is shrinked below the min width of some divs.

## Steps to Reproduce
1. Visit https://hugo-toha.github.io/.
2. Open developer tools.
3. Reduce the width to less than 618px.

### Screenshots
![1](https://user-images.githubusercontent.com/51094650/117482690-04adf880-af65-11eb-8b16-588d8bda5781.png)
![2](https://user-images.githubusercontent.com/51094650/117482693-05468f00-af65-11eb-8032-08a6bfcc81c6.png)

**Comment by sandstormkeshav** [comment]
I've seen this as well. Not sure how to fix it either :(
