### ISSUE TITLE
Error building Question. 

### ISSUE THREAD

**Issue by pinemmatthew** [hugo-toha/toha#315]
### Question

Hey All,
so I have been having trouble recently making this site. Everytime I am trying to build the website I am getting a trace error message like so:

Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:39:8: executing "index.html" at <partial "sections="" home.html"="" .="">: error calling partial: "/home/matthew/go/src/awesomeProject29/themes/toha/layouts/partials/sections/home.html:29:31": execute of template failed: template: partials/sections/home.html:29:31: executing "partials/sections/home.html" at <$authorImage.Fit>: nil pointer evaluating resource.Resource.Fit

any advice on how to fix this? I've been following the getting started instructions.

**Comment by hossainemruz** [comment]
@pinemmatthew Can you please point me to your repo so that I can take a look?

**Comment by Nosliwnayr** [comment]
Same issue, repo available here https://github.com/Nosliwnayr/personal-website.
Should throw the same error when building.

If it helps, I'm running `hugo v0.83.1-5AFE0A57+extended linux/amd64` on Fedora 34.

**Comment by hossainemruz** [comment]
@Nosliwnayr Move your `images` folder from `static` directory into `assets` directory.

**Comment by Nosliwnayr** [comment]
Ahhh okay thanks! I was following along with the instructions here: https://toha-guides.netlify.app/posts/getting-started/prepare-site/ and since the resume went into static I thought the photo would go there as well.
It might be worth updating those instructions to mention where to put the photo for that step?

**Comment by hossainemruz** [comment]
@pinemmatthew I am suspecting you are facing same problem as @Nosliwnayr . I am closing this issue. Feel free to reopen if you still face this issue.
