### ISSUE TITLE
support jquery-pjax

### ISSUE THREAD

**Issue by GaHoWong** [hugo-toha/toha#319]
Hello, is there any plan to support jquery-pjax?

**Comment by hossainemruz** [comment]
Can you please explain the usecase?

**Comment by GaHoWong** [comment]
The advantages of pajx are obvious:
(1) It can reduce the pressure on the server.
(2) Optimize the page jump experience.
(3) When clicking on other pages, there will be no sudden flashing
(4) The background music will not be paused (my urgent need)
The disadvantages can almost be ignored:
(1) Some low-version browsers (such as Internet Explorer) are not supported.
(2) Complicated server-side processing.

In general, it is very worth recommending, especially for websites like Hugo blog sites that only change the main content in most cases. The key is that it is simple to use and low cost of learning. The pjax github homepage has been introduced in detail. If you want to know more, you can look at the source code [1].
Many themes currently on Jekyll, WordPress, and hexo have applications. The hugo theme application is rarely seen.

I very much look forward to applying this technology to the toha theme. When I use aplayer[2], I can click on other articles without pausing or refreshing the music playback. When i use aplayer

In my heart, toha is just a little bit perfect
Reference connection:
[1]jquery-pjax: https://github.com/defunkt/jquery-pjax
[2]aplayer: https://aplayer.js.org/
[3] Hugo blog example using pajx: https://github.com/vvc-Dream/hugo-maupassant-pjax
[4] Examples of websites using pajx:
https://inkss.cn/
https://mengd.lete114.top/

I am not good at writing code, I hope this can help you.

**Comment by hossainemruz** [comment]
@GaHoWong sound interesting. However, it seems the `jquery-pjax` project is not actively maintain anymore.

> ## Status of this project
>jquery-pjax is largely unmaintained at this point. It might continue to receive important bug fixes, but its feature set is frozen and it's unlikely that it will get new features or enhancements.

I don't think we should include this into the theme. Probably, we should find an alternative that provides these benefits and actively maintained.

**Comment by GaHoWong** [comment]
> @GaHoWong sound interesting. However, it seems the `jquery-pjax` project is not actively maintain anymore.
> 
> > ## Status of this project
> > jquery-pjax is largely unmaintained at this point. It might continue to receive important bug fixes, but its feature set is frozen and it's unlikely that it will get new features or enhancements.
> 
> I don't think we should include this into the theme. Probably, we should find an alternative that provides these benefits and actively maintained.

Maybe a better alternative can be found, but at the moment I still don’t know any solution.
