### ISSUE TITLE
bug: Badges and Circular progress value not visible in about section

### ISSUE THREAD

**Issue by sushil11th** [hugo-toha/toha#325]
## Expected Behavior
Badges and Circular progress value should visible in about section as it is in example/demo site 
https://hugo-toha.github.io/#about
## Current Behavior
Badges and Circular progress value not visible in about section 

### Screenshots
![bug](https://user-images.githubusercontent.com/26380084/119385242-7f0ba600-bce3-11eb-8bd8-43158a7ad160.PNG)

**Comment by hossainemruz** [comment]
I can see them.
![image](https://user-images.githubusercontent.com/12577390/119442711-26bbbf00-bd4a-11eb-9f15-6ff966bd4ceb.png)

**Comment by sushil11th** [comment]
In the local setup that was downloaded from the source branch, it is not visible for all browsers.  As it is showing on the site below:

https://hugo-toha.github.io/#about

The screenshot is of the local setup.

**Comment by dugite-code** [comment]
@sushil11th I was experiencing the same issue and had to update my local copy of the theme, looks like I go a copy in the middle of a bunch of changes.
