### ISSUE TITLE
Feature Request: Social Media Featured Image Embed

### ISSUE THREAD

**Issue by kevinlinxc** [hugo-toha/toha#327]
### Describe the solution you'd like

 Provide a clear and concise description of what you want to happen.
When you share a link on social media (e.g. facebook messenger, Discord) there will be an image preview, sometimes called featured image/embed preview, and I'm wondering if that feature is available for github pages with toha/hugo.

### Describe alternatives you've considered
I tried using the preview_image: in config.yaml and it didn't work.

**Comment by hossainemruz** [comment]
This already cover in this FR: https://github.com/hugo-toha/toha/issues/81

It is now the highest priority FR for the theme and will be available in next release.

**Comment by hossainemruz** [comment]
Added  in #333
