### ISSUE TITLE
Difference ressource.Resize vs ressource.Fit

### ISSUE THREAD

**Issue by vlebert** [hugo-toha/toha#340]
Hi,

First of all, congratulation for your wonderful theme and documentation. I tried various themes and it is by far the most complete (and visualy nice) theme I played with

After going deeper into Hugo code, I am wondering what is the difference between ressource.Resize and ressource.Fit
https://gohugo.io/content-management/image-processing/

For example, for the logos of the skill section, I realize that despite the use of ressource.Fit in your code (24x24px), the full  original picture is downloaded when loading the page.

Wouldn't it be more efficient to use ressource.Resize. Moreover, could you explain to me what is actually doing ressource.Fit.
I searched a bit for detailled explanation but wasn't successfull.

Thanks
Valérian

**Comment by hossainemruz** [comment]
@vlebert `resource.Fit` will fit the image on the given dimension while keeping the aspect ratio. For example, I have a 600x400 (rectangular) image which I want to use in a 24x24 (square) frame. Now, `resource.Fit` will resize the image into 24x24 dimension and also crop the image to keep the aspect ratio. On the other hand, the `resource.Resize` will only resize the image into `24x24` dimension but it will not crop the image. It won't preserve the aspect ratio.

**Comment by vlebert** [comment]
Hi @hossainemruz 

Thank you for the answer. I understand the expected behaviour. However I am not sure it corresponds to what I observe. Let's take for example a rectangle Python logo :
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_logo_and_wordmark.svg/2560px-Python_logo_and_wordmark.svg.png

I downloaded this one and used in in "skills" section. As a result:

- The aspect ratio is changed
- The original picture is downloaded by the browser and not a 24x24 version

Did I miss something?
![image](https://user-images.githubusercontent.com/49779177/120598908-2193f980-c447-11eb-9806-3f8ca8d15d45.png)

**Comment by vlebert** [comment]
I did some tests changing the original `skill.html` partial:

**original**
```
        {{ if .logo }}
          {{ $logoImage := resources.Get .logo }}

          {{/*  svg don't support "Fit" operation   */}}
          {{ if ne $logoImage.MediaType.SubType "svg" }}
            {{ $logoImage := $logoImage.Fit "24x24" }}
          {{ end }}

          <img class="card-img-xs" src="{{ $logoImage.RelPermalink }}" alt="{{ .name }}" />
        {{ end }}
        <h5 class="card-title">{{ .name }}</h5>
```

**modified** (remove the SVG simpification as a simplification for the test)

```
      <div class="card-head d-flex">
        {{ if .logo }}
          {{ $logoImage := resources.Get .logo }}

          {{ with ($logoImage.Fit "24x24") }}
          <img class="card-img-xs" src="{{ .RelPermalink }}" alt="toto" />
          {{ end }} 
        {{ end }}
        <h5 class="card-title">{{ .name }}</h5>
      </div>
```

With the modified version, only a small version of the logo is downloaded which is expected
![image](https://user-images.githubusercontent.com/49779177/120600100-aa5f6500-c448-11eb-9210-c2838aa930a8.png)

I guess `{{ $logoImage := $logoImage.Fit "24x24" }}` does not work outside the loop. Or maybe this in not the proper way of getting the modified version of the picture

**Comment by vlebert** [comment]
Maybe this can help:

https://discourse.gohugo.io/t/solved-unsure-how-to-set-variable-value-after-declaring/1443

**Comment by hossainemruz** [comment]
It seem the issue with this line.
```
{{ $logoImage := $logoImage.Fit "24x24" }}
```

The variable has been re-declared. It should work with, `{{ $logoImage = $logoImage.Fit "24x24" }}`. I will test to be sure.

**Comment by vlebert** [comment]
Thanks, I tested your solution and it fixes the issue

I proposed you a pull request fixing all .Fit occurences (4)
