### ISSUE TITLE
Feature Request: prefers-color-scheme support

### ISSUE THREAD

**Issue by networkpanic** [hugo-toha/toha#349]
### Describe the solution you'd like

It would be nice to set 2 different color schemes which apply based on the visitors desktop settings.
[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) would allow us to do that

**Comment by hossainemruz** [comment]
Sure I will love to add this feature. I am planning for a significant rewrite of the theme in version `4.0.0`. Specially, I want to move to SCCS instead of CSS to ensure manageability and consistency. After that, we can work on this feature.

**Comment by donfiguerres** [comment]
I think this is a duplicate of #59 .

**Comment by Chow-Ray** [comment]
> Sure I will love to add this feature. I am planning for a significant rewrite of the theme in version . Specially, I want to move to SCCS instead of CSS to ensure manageability and consistency. After that, we can work on this feature.`4.0.0`

When will version 4.0.0 be released? Special look forward to。

**Comment by hossainemruz** [comment]
No planned timeline yet. I am busy with some other stuffs. Expect minimum 3-4 months delay.

**Comment by Rihoj** [comment]
@hossainemruz Do you have anything planned out and willing to share to see if this community could help progress the timeline to meet your vision?

**Comment by hossainemruz** [comment]
Actually, I don't have a plan yet.
