### ISSUE TITLE
Newsletter functionality

### ISSUE THREAD

**Issue by oscarmrom** [hugo-toha/toha#35]
Hello, 

I wanted to understand the functionality of the newsletter subscription in the footer:

![image](https://user-images.githubusercontent.com/26697231/86928745-f7389f80-c102-11ea-9029-be41b1895f0d.png)

How do you configure this, how is this expected to be used? I'm sorry if I missed the documentation on this. If you could link me that would be great!

**Comment by hossainemruz** [comment]
Current, it doesn't work. I will add this functionality in future.

**Comment by oscarmrom** [comment]
Okay, cool. I've commented it out from the footer on my end for the time being. Thank you!

**Comment by hossainemruz** [comment]
@oscarmrom You can now hide the newsletter section using `config.yaml`. Ref: #48

**Comment by PabloBiotech2020** [comment]
If I understand it corresctly, HUGO already auto generates RSS feeds for evert website, so couldnt this be done in a super cool, easy and standards compliant way if you simply redirected users to a site such as blogtrotter that notifies users on every new RSS item? I know, it wouldnt be the same as a full fledged newsletter but it would suffice to keep people informed of your blog changes, and, frankly, I think if people really need a real, ful fledged newsletter they would already be using something of the likes of mailchimp

**Comment by MarionMoseby** [comment]
If I understand it corresctly, HUGO already auto generates RSS feeds for every website, so couldnt this be done in a super cool, easy and standards compliant way if you simply redirected users to a site such as blogtrotter that notifies users on every new RSS item? I know, it wouldnt be the same as a full fledged newsletter but it would suffice to keep people informed of your blog changes, and, frankly, I think if people really need a real, ful fledged newsletter they would already be using something of the likes of mailchimp

**Comment by hossainemruz** [comment]
Added support for [mailchimp](https://mailchimp.com/) in #308.
