### ISSUE TITLE
Followup: Background image in low quality

### ISSUE THREAD

**Issue by hangangmagazine** [hugo-toha/toha#351]
### Question
Hello, I saw that there was a fix here: https://github.com/hugo-toha/toha/issues/70

But I still have a blurry background image when I view it in mobile iOS as well as Developer tools Inspect in Firefox

here's what it looks like on desktop

![image](https://user-images.githubusercontent.com/75532219/121360351-4caea980-c96f-11eb-8052-b22df3c5c277.png)

And here on mobile

![image](https://user-images.githubusercontent.com/75532219/121360371-520bf400-c96f-11eb-98e7-57c420b2b00a.png)

I tried to add 

```
-webkit-background-size: cover;
-moz-background-size: cover;
```

But it didn't make a difference. Thank you for any assistance.

**Comment by hossainemruz** [comment]
You can disable blur following this guideline.
https://toha-guides.netlify.app/posts/customizing/customize-css/
