### ISSUE TITLE
bug: Google Analytics 4 is not supported

### ISSUE THREAD

**Issue by gilcrest** [hugo-toha/toha#352]
I want to start by saying thank you - I love this theme and have found your docs fantastic!

Unfortunately, I'm not able to use **Google Analytics v4** with the toha theme. **Google Analytics 4** is currently the default for new accounts.

Looking at your layouts, I see the following code in both the `index.html` and the `baseof.html` files: 

```html
    {{ if site.GoogleAnalytics }}
        {{ template "_internal/google_analytics_async.html" . }}
    {{ end }}
```
From the [HUGO documentation](https://gohugo.io/templates/internal/#use-the-google-analytics-template), for Google Analytics v4:

> When using Google Analytics v4 use `_internal/google_analytics.html`.

The `_internal/google_analytics_async.html` which toha is using seems to only work with v3.

As a workaround, you can still get the old v3 IDs by following [this post](https://support.google.com/analytics/answer/10269537), but you can't leverage a lot of the stuff that is in v4...

Thanks again!

Dan

**Comment by hossainemruz** [comment]
@gilcrest Thank you for reporting it. As you have found the root cause, can you please send a PR? I will be happy to review. Otherwise, you have to wait until I get some time to work on this.

**Comment by gilcrest** [comment]
Hi @hossainemruz - yes. I'm going to test today if you can use the v3 with `_internal/google_analytics.html`. If so, the change is trivial. If not, I have to add logic and having not worked with HUGO templating yet, might take me a minute. Stay tuned!

**Comment by gilcrest** [comment]
Ok, I'm going to add a PR. After researching, the change is trivial, but should still work for both v3 and v4.

Here's some of the issues where they're discussing the Google Analytics v4 changes: 

[Add support for google analytics v4 #8287](https://github.com/gohugoio/hugo/pull/8287)

There are a number of issues linked to this, but after reading through them (particularly [this issue](https://github.com/gohugoio/hugo/pull/8264)) it seems they're leaving the `_async` template in place for legacy purposes, but are moving to the v4 method going forward as Google is now not adding features to the old v3 method and trying to get everyone to move over.
