### ISSUE TITLE
About section summary should take up entire page width if no soft skills are given

### ISSUE THREAD

**Issue by will-hou** [hugo-toha/toha#368]
Before filing an issue, please review the following:
* Existing Features: https://github.com/hossainemruz/toha#features ✅
* Project Roadmap: https://github.com/hossainemruz/toha#project-roadmap ✅

### Describe the solution you'd like

I've been building my personal site with Toha and really enjoying everything so far. However, I don't plan on including any soft skill "circles" in my About section. If I don't specify any `softSkills` in my `about.yaml` file, the template leaves a big chunk of whitespace to the right of the summary.

![current_about_section_with_whitespace](https://user-images.githubusercontent.com/23201789/124335212-7910ac80-db4e-11eb-93f2-39f92802688b.png)

I think it would look nicer if the summary took up the entire width of the section if no soft skills are specified like what's pictured below. 

![about_section_without_whitespace](https://user-images.githubusercontent.com/23201789/124335245-934a8a80-db4e-11eb-9c44-d1d55c31932f.png)

~~I am very new to Hugo templates but I believe the following addition to [line 14 of `about.html`](https://github.com/hugo-toha/toha/blob/4099f4f1e65299866e739b3be43b6d147ab16e61/layouts/partials/sections/about.html#L14) would implement this feature nicely.~~ 

The following solution is now outdated as I forgot to consider the presence of [badges](https://github.com/hugo-toha/toha/pull/307). Please see #369 for the updated code.  

![proposed_solution(1)](https://user-images.githubusercontent.com/23201789/124335670-e4a74980-db4f-11eb-8f91-d89e5abe1a9a.png)

In the future, it may also be nice to give the user an option to include a rounded profile picture to the right instead of soft skills. But that might be an idea for a different issue. 

Would be happy to make a PR with this change if all looks good. Thanks!

**Comment by hossainemruz** [comment]
Sound good to me. Can you please sent a PR?
