### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ahmadmssm** [hugo-toha/toha#371]
## Expected Behavior
The website to be deployed with GitHub actions

## Current Behavior
Error

```
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:65:18: executing "index.html" at <partial (printf "sections/%s.html" (replace (lower .section.id) " " "-")) .>: error calling partial: execute of template failed: template: partials/sections/skills.html:13:11: executing "partials/sections/skills.html" at <partial "cards/skill.html" .>: error calling partial: "/home/runner/work/ahmadmssm.github.io/ahmadmssm.github.io/themes/toha/layouts/partials/cards/skill.html:10:38": execute of template failed: template: partials/cards/skill.html:10:38: executing "partials/cards/skill.html" at <$logoImage.Fit>: error calling Fit: *resources.genericResource is not an image
```

## Steps to Reproduce
Followed this [tutorial](https://toha-guides.netlify.app/posts/getting-started/github-pages/).

**Comment by ahmadmssm** [comment]
@hossainemruz Can you help here please ?, Thanks in advance.

**Comment by hossainemruz** [comment]
This line is causing the issue: https://github.com/ahmadmssm/ahmadmssm.github.io/blob/c9f279583d93575e7c6c80fd11093b1e687a62b7/data/en/sections/skills.yaml#L20

`webp` format not yet supported by Hugo image processing. Please, use `png`, `jpg`, or `jpeg` image.

**Comment by ahmadmssm** [comment]
Thank you very much, It is working now.
Can I ask you one more question, The background image is always white with the default and custom images, although it is showing as expected when testing locally.

**Comment by hossainemruz** [comment]
You forgot to change the `baseURL` in your `config.yaml` file

**Comment by ahmadmssm** [comment]
Thank you so much.

**Comment by hossainemruz** [comment]
My pleasure
