### ISSUE TITLE
Hero image and posts bug

### ISSUE THREAD

**Issue by ahmadmssm** [hugo-toha/toha#379]
Hello,

I followed this [article](https://toha-guides.netlify.app/posts/writing-posts/organizing/category/) but I faced some issues where I couldn't set a custom hero image except by doing the following.
1. The here image should be named here, so I can't use a custom name.
2. It should be in the post folder, and any other path will not work even `assets/images` and It will always fall back to the default hero image.
3. The post name should be `index.md` other than that it will show the default hero image even if the previous points are satisfied.

The other issue is that recent posts always show the following, if I have only one post.

<img width="1127" alt="Screen Shot 2021-07-24 at 5 11 44 PM" src="https://user-images.githubusercontent.com/26115953/126872792-a49085c1-600c-4d6e-86df-29d2a1c390e7.png">

Please let me know If I'm doing something wrong.
Thanks in advance.

**Comment by hossainemruz** [comment]
You can use your custom hero. Check this sample post.
https://raw.githubusercontent.com/hugo-toha/hugo-toha.github.io/source/content/posts/category/sub-category/rich-content/index.md

**Comment by ahmadmssm** [comment]
Thank you, I tried but It didn't work

**Comment by hossainemruz** [comment]
Can you point me to your post where you tried with custom hero image? It should work. It working on the  demo site.

**Comment by Rihoj** [comment]
I am having the same issue. My directory structure was content -> posts -> file.md, I have tried placing the image files in assets, static, and in content -> posts -> images. I found I had to have the following:
1. A sub folder under post.
2. The file had to be named index.md
3. and the image had to be located in the sub folder in another folder called images. 

I was not required to have image named hero if the above criteria was met.

**Comment by anverbogatov** [comment]
Hi there,
Customization of hero image do not work for me either. 

In my case, I am mostly interested in changing hero image through post's front-matter. In that case, I think the problem is in `toha/layouts/partials/helpers/get-hero.html`. Default hero image load logic looks like this:
```go
{{ if .Params.hero }}
  {{ $heroImage = .Page.Resources.GetMatch .Params.hero }}
{{ end }}
```
But when you change `heroImage` init to:
```go
{{ $heroImage = resources.Get .Params.hero }}
```
images on posts become customizable through front-matter.

**Comment by Petrichor31** [comment]
@anverbogatov Hi, sorry but I cannot get your fix work.
What is the complete get-hero.html?
Should I put some particular information in the frontmatter of my .md files (except hero: image.svg)?
Thank you

**Comment by anverbogatov** [comment]
Hey @Petrichor31 , sorry for long response. So, here is my configuration. 
1) I have created an override for `get-hero.html` file in my project's folder in: `[project-root]/layouts/partials/helpers/get-hero.html`
2) I have put following content to the file:
```
{{/* check if there is any hero image in the same folder as the markdown file */}}
{{ $heroImage := .Page.Resources.GetMatch "hero.{jpg,png,svg}"}}

{{/*  if hero image is specified in the page front-matter, then use that  */}}
{{ if .Params.hero }}
  {{ $heroImage = resources.Get .Params.hero }}
{{ end }}
{{ .Scratch.Set "heroScratch" $heroImage }}

{{/* if hero image is not provided, then use the default hero image */}}
{{ if not $heroImage }}
  {{ $heroImage := resources.Get "images/default-hero.jpg"}}
  {{ .Scratch.Set "heroScratch" $heroImage }}
{{ end }}

{{ $heroImage := .Scratch.Get "heroScratch" }}

{{/* resize hero image. don't resize if the image is an svg */}}
{{ if and $heroImage (ne $heroImage.MediaType.SubType "svg") }}
  {{ $heroImage := $heroImage.Resize "148x" }}
{{ end }}

{{/*  return the hero image  */}}
{{ return $heroImage.RelPermalink }}
```
3) I have put images that I have used as covers to my posts to `assets` folder
4) In my posts md files I have used `hero: path_to_image_in_assets_folder` property in post definition part

And that worked for me. 
You can find full commit with my fix here: https://github.com/anverbogatov/anverbogatov.github.io/commit/3ae814081b48c68875daa50ba8f8d00a5093dcd0

And you can see it in action here: https://www.anverbogatov.com (just scroll down to the Recent posts section)

I hope that will help. 🤝

**Comment by Petrichor31** [comment]
@anverbogatov thanks a lot, that worked for me!

**Comment by anverbogatov** [comment]
@Petrichor31 really nice too hear that!! 🤝

**Comment by TimJones** [comment]
@anverbogatov Thanks for the workaround! Are you able to create a PR to fix this bug in the theme directly? If not I'd be happy to with your consent.

**Comment by anverbogatov** [comment]
Hi Tim, yes, please do a PR if you want. I am not sure if that is the right way to fix the theme (for me it was just a workaround). But if you think it is - please create PR and fix the problem :-)

**Comment by langerdennis** [comment]
> You can use your custom hero. Check this sample post.
> https://raw.githubusercontent.com/hugo-toha/hugo-toha.github.io/source/content/posts/category/sub-category/rich-content/index.md

I am facing the same problem as the OP and it is working for me as long as the post itself is placed in its own subfolder (not necessarily category). The example you are linking to fulfills that requirement - that file is even called index.md, which was not necessary for me. According to the documentation this folder structure should however not be necessary... I can live with this workaround, but assume this is not the intended behavior.
