### ISSUE TITLE
My website is never created.

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#380]
I followed steps [here](https://toha-guides.netlify.app/posts/getting-started/github-pages/). I tried it about 5 times, but all the times I failed except I just use the default setting. Could you see what is wrong? My repository is [here](https://github.com/IhnwhiHeo/ihnwhiheo.github.io). You can see the error message below. Thank you.

<img width="1440" alt="스크린샷 2021-07-25 오후 3 16 24" src="https://user-images.githubusercontent.com/60255083/126889694-047cdba0-487e-4e61-914a-16f282684bbf.png">

**Comment by hossainemruz** [comment]
I don't see your `assets` folder with the images.

**Comment by IhnwhiHeo** [comment]
Thanks for your check. I also see that. However, why it isn't created, although I have those files on my local drive? I pushed from the origin, but those assets are not copied. Do you have any ideas for a solution?

Thank you.

**Comment by hossainemruz** [comment]
I am suspecting you haven't committed those files into GitHub.

**Comment by IhnwhiHeo** [comment]
I think I did. I tried the following at the local root:
``git add .``
``git commit -m "updates"``
``git push origin source``
Are there anything I missed?

**Comment by hossainemruz** [comment]
I am not sure. Can you post a screenshot of your local sate?

**Comment by IhnwhiHeo** [comment]
Sure. Here it is:
<img width="778" alt="스크린샷 2021-07-25 오후 8 16 46" src="https://user-images.githubusercontent.com/60255083/126897171-c3b70441-900e-436c-a2d6-d46b583a5679.png">

**Comment by IhnwhiHeo** [comment]
Well, I tried again. Still, the themes/toha files are not pushed. It's weird.
Also, do you know what these messages mean by: remote: Permission to hugo-toha/toha.git denied to IhnwhiHeo.
fatal: unable to access 'https://github.com/hugo-toha/toha.git/': The requested URL returned error: 403 ?

**Comment by hossainemruz** [comment]
Ok. You don't have the `assets` folder locally too. Create a directory `assets/images`  in your repo. Then, put your images there. Test your site locally by running `hugo server -w`. If it compiles without any error, then push the changes into Github.

**Comment by IhnwhiHeo** [comment]
When I ran the website locally, it works perfectly okay. Once I push to the remote source, however, it does not copy assets. Did I miss anything?

**Comment by IhnwhiHeo** [comment]
I tried again. With the default step-by-step explanation, it works. Once I use my files, however, the website does not work, although it works locally.

**Comment by hossainemruz** [comment]
Fork this repo and rename to your username: https://github.com/hugo-toha/hugo-toha.github.io

**Comment by IhnwhiHeo** [comment]
@hossainemruz 
Thanks for your replies. I successfully figured out the cause. I should deal with folders/files NOT in the theme folder. If I work outside of it, it works okay. So, now the website is successfully rendered.. I realized this after more than 10 trials... Now, let me close this comment. Thanks for your help!
