### ISSUE TITLE
bug--BUG that cannot use GIF avatar

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#392]
## Expected Behavior

If  set the code like this, it will cause the GIF format avatar to be unusable。
https://github.com/hugo-toha/toha/blob/8f239a0ddc8af36a64881925108a443d65409380/layouts/partials/sections/home.html#L108

##  Solution

Set the code as follows to solve the problem. It is up to you to decide whether to fix it.
```
<img src="{{ $authorImage | relURL }}"
```
### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by Rihoj** [comment]
This seems to be related to #209 as well. After doing some digging it appears this is more of a limitation of the imaging code that is in hugo itself. You can reference gohugoio/hugo#5030

In regards to your solution, this means all the image manipulation that is performed on the asset would no longer be performed, and the file would not be stored in the `assets` folder, but instead in the `static` folder. 

If @hossainemruz would like I could update the code around that with the following check and then write up a post on the guide in reference to gifs not getting the image processing and that it needs to be placed in the static folder. However, this seems like a hack and I don't want to clutter the code with items like this.

Condition to check for gif
```
{{ if eq $image.MediaType.SubType "gif" }}
```

**Comment by hossainemruz** [comment]
>gifs not getting the image processing and that it needs to be placed in the static folder.

You can put the `gifs` in the assets folder even if the  image processing are not applied on them. @Rihoj  go ahead with the hack. I will be happy to accept.

**Comment by Chow-Ray** [comment]
@Rihoj @hossainemruz 
Thank you very much for finding a way to solve the problem for me, and hope to solve this problem in the future. I am not a professional programmer, but I like Toha very much. Because I like it, I did a Chinese translation for it. I hope it will get better and better. Thank you excellent programmers for making such an excellent theme.

**Comment by Rihoj** [comment]
> > gifs not getting the image processing and that it needs to be placed in the static folder.
> 
> You can put the `gifs` in the assets folder even if the image processing are not being applied on them.

This was specifically targeted at using `| relURL` not appling the image processing and being in the assests folder. Where as using `.RelPermalink` does the intended behavior.
