### ISSUE TITLE
Flag 404 bug

### ISSUE THREAD

**Issue by Rihoj** [hugo-toha/toha#399]
## Expected Behavior
Either don't try to load the files or include them in the theme.

## Current Behavior
Tries to load svgs for the flags, that don't exist

## Possible Solution
Check for files first, or just include them in the theme

## Steps to Reproduce
1. If you open the Devtools network or console you will be able to see 258 errors of 404s https://rayprogramming.com

### Screenshots
![image](https://user-images.githubusercontent.com/1520296/130113680-11cbad26-d77e-4804-a897-fe5c9671122b.png)

### Browsers Affected
Untested on anything other than chrome
- [ x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by Nirzak** [comment]
Hi, I don't see any such errors on my end. May be you should upgrade your themes to the latest one.
![Screenshot (3770)](https://user-images.githubusercontent.com/11460645/136657053-29f981a5-90e3-41ab-9b6c-d4ae328582ec.png)

**Comment by hossainemruz** [comment]
This should be fixed now. Please, try upgrading to the latest release. Feel free to reopen if not fixed.
