### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HabibRh26** [hugo-toha/toha#405]
## Expected Behavior

I used the theme to build my portfolio site(almost 9 months ago), In mobile browser, the nav icon should close auto after selecting an item from menu. </br>
My site link: [here](https://habibrh26.github.io/#NaN)

## Current Behavior

From mobile(xiaomi-android) browser, once I click the nav icon and select a menu it does not close automatically and when I select one menu two menu is shown active
## Steps to Reproduce

1.  Just open my site from mobile browser
2.
3.
4.

### Screenshots

![new_gif](https://user-images.githubusercontent.com/47397271/131240810-1becd01d-1af9-4173-90f0-1e2cc39240a2.gif)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

This is more related to the site that i built using this theme, when I opened the site using mobile browser, the navigation icon is not working correctly, the attached gif might help understand the issue.

**Comment by hossainemruz** [comment]
Can you please try upgrading to the latest version. This should be fixed.
