### ISSUE TITLE
Serve Font Awesome locally

### ISSUE THREAD

**Issue by DocKDE** [hugo-toha/toha#414]
Hi,
I'd like to serve Font Awesome locally without using the cloudflare CDN for privacy reasons. I downloaded the appropriate files and put the `webfonts` folder and `all.min.css` in the `static` directory. I then edited the `layouts/partials/header.html` and replaced the line 
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />
```
with 
```
<link href="css/all.min.css" rel="stylesheet"> 
```
This will result in the social icons in the `about` section to be rendered correctly. However, the plus/minus icons indicating the structure of the posts in the `posts` section are not displayed. I'm not well versed in `html` and `CSS`, do I have to edit some other file for that to work or what else am I missing here?

**Comment by hossainemruz** [comment]
Can you check the console log in `posts` page? You can also provide a link to your website so I can take a look.

**Comment by hossainemruz** [comment]
Add this to `header.html` too.
```
<link rel="stylesheet" href="css/all.min.css" >
```

**Comment by DocKDE** [comment]
Tried that but it didn't help.
