### ISSUE TITLE
Separator on navigation bar missing

### ISSUE THREAD

**Issue by DocKDE** [hugo-toha/toha#419]
Hi, I noticed recently that the separator in the navigation bar does not appear on my site as opposed to the example site. I didn't change anything in the css there so I'm not sure why that is.
My site is at https://thedoctor.codeberg.page/ and the source code can be found here: https://codeberg.org/theDoctor/pages

**Comment by Rihoj** [comment]
Well, the logic to enable the divider is as follows:
```
{{ $addNavbarSeparator:= false }}

{{/*  If "blog" feature is enabled, then add navbar separator  */}}
{{ if site.Params.features.blog.enable }}
    {{ $addNavbarSeparator = true }}
{{ end }}

{{/*  If "notes" feature is enabled, then add navbar separator  */}}
{{ if site.Params.features.notes.enable }}
    {{ $addNavbarSeparator = true }}
{{ end }}

{{/*  If site has custom menus, then add navbar separator  */}}
{{ $customMenus := site.Params.customMenus }}
{{ if (index site.Data site.Language.Lang).site.customMenus }}
  {{ $customMenus = (index site.Data site.Language.Lang).site.customMenus }}
{{ end }}

{{ if $customMenus }}
    {{ if gt (len $customMenus) 0 }}
        {{ $addNavbarSeparator = true }}
    {{ end }}
{{ end }}

{{ return $addNavbarSeparator }}
```

Without being able to see your config files I do not think I can help you beyond that.

**Comment by DocKDE** [comment]
Sorry, I didn't realize the config wasn't included in the code I posted. I had a look at the logic and realized that I hadn't set `features` section in the `config.yaml` file and also not enabled blog posts in there. This is not quite obvious from the docs as there is a top-level option for enabling blog posts already which I had set.
Anyway, I figured it out now, thanks!
