### ISSUE TITLE
Implement search functionality of sidebar

### ISSUE THREAD

**Issue by hossainemruz** [hugo-toha/toha#42]

**Comment by inhundreds** [comment]
Hello, I'm looking to tackle this issue. There is nothing already implemented, right? I could find only the search box but not the logic.

Thanks,
Diego

**Comment by hossainemruz** [comment]
Yes. That's right. I haven't implemented the logic yet.

**Comment by hossainemruz** [comment]
Renamed the issue to avoid confusion.

**Comment by inhundreds** [comment]
Can I give it a try? The sidebar is both in /posts page and in the single post page: at first I will implement the search functionality only on the former (if it is ok for you).

Pls let me know,
Diego

**Comment by hossainemruz** [comment]
Sure. That will be great.

**Comment by hossainemruz** [comment]
done in #227
