### ISSUE TITLE
Dark theme button

### ISSUE THREAD

**Issue by amankumar11** [hugo-toha/toha#430]
### Describe the solution you'd like

will make a button in the nav, clicking which the website would go in dark theme

.

I would like to work on this feature under Hacktoberfest label

**Comment by hossainemruz** [comment]
Sure go on.

**Comment by amankumar11** [comment]
I am not able to run the site, the HTML written is something very different can you pls guide me how to do the setup so that i can run it on my machine.

**Comment by MarionMoseby** [comment]
@amankumar11 What do you not understand? Maybe the issue is that this is a HUGO template, and not plain HTML?

**Comment by amankumar11** [comment]
Yes, how to setup a hugo template?

**Comment by MarionMoseby** [comment]
IMHO this might be too complicated for a first issue, but you can check [Toha's offcicial guide](https://toha-guides.netlify.app/posts/getting-started/prepare-site/)

**Comment by yas-sisodia** [comment]
@amankumar11 please allow me to work on this project

**Comment by amankumar11** [comment]
ok, you can start @yas-sisodia

**Comment by NSerbin** [comment]
Any updates ?
