### ISSUE TITLE
Why does the top menu disappear on the Blog / Posts / Reading views?

### ISSUE THREAD

**Issue by pboling** [hugo-toha/toha#435]
### Question

I've tried to understand why this might be, but I can't.  It is a limitation of Hugo?  Or was is a design decision?  I love everything about this theme, except that.

**Comment by hossainemruz** [comment]
What do you mean by top menu disappear? Can you please share a screenshot?

**Comment by hossainemruz** [comment]
It was by design. The home page and post pages uses separate top bar. I think we should probably make the two topbar identical.

**Comment by LukeEvansTech** [comment]
Just to chime in, would absolutely love this to be implemented.

Happy to take a stab but my skills in Hugo are still relatively new.

@hossainemruz would you mind pointing me in the right direction of where to look and I'm happy to give it a go!
