### ISSUE TITLE
Author image stretched

### ISSUE THREAD

**Issue by EliiseS** [hugo-toha/toha#44]
### Description

The author image is being stretched instead of being fitted in the circle by the middle point, which is what I'd expect. 

If this is not possible to fix, I'd be nice to know what dimensions the picture should be.

### Visualization

![image](https://user-images.githubusercontent.com/12761692/87833640-40fe5400-c880-11ea-8123-24d219dd3839.png)

**Comment by hossainemruz** [comment]
Try providing a square (i.e. 512x512) image.

**Comment by EliiseS** [comment]
Yeah! That's better :P 

I think if it's possible this could a nice to have fix. I however remember something very vaguely about this being difficult with css.

**Comment by hossainemruz** [comment]
There should be a way to automatically adjust the image. Don't know currently. I have to check.

**Comment by StefanTobler** [comment]
@EliiseS what is the resolution of your before image? Maybe I can look into it.

**Comment by EliiseS** [comment]
It's 2208 x 2944 @EliiseS

**Comment by alex-bezek** [comment]
while good image optimization is a staple of web performance, don't these new static site generators have the ability to help us avoid having to remember to optimize things? Coming from gatsby i'm used to each image being optimized without much user input. Is the problem that this theme uses the statics repo vs page bundles?

https://gohugo.io/content-management/image-processing/

> The image is a Page Resource, and the processing methods listed below do not work on images inside your /static folder.

I'm new to hugo so i'm unclear if this is relevant to images on the home page, but at first glance it seems like it would be nice if we could update to use images in the hugo static processing pipeline across the board to benefit from all the optimizations. 

If you agree, with a little guidance I'd be up for looking into how we could use this while maintaining passivity.
