### ISSUE TITLE
Is there any idea of what is creating an "Access is denied" error when starting a hugo server with toha?

### ISSUE THREAD

**Issue by Chandler-Stewart** [hugo-toha/toha#440]
### Question
I keep running into this error, including when I started from scratch. I get an Access denied error, and it seems to happen with images. The error after running `hugo server` from a site created from scratch (ie, after `hugo new site` command, then `git submodule add https://github.com/hossainemruz/toha.git themes/toha`)

Error log:
`C:\Users\John\Documents\john-doe.github.io>hugo server
Start building sites …
hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
ERROR 2021/10/19 17:38:47 render of "page" failed: execute of template failed: template: _default/search.html:41:8: executing "_default/search.html" at <partial $footerTemplate .>: error calling partial: "C:\Users\John\Documents\john-doe.github.io\themes\toha\layouts\partials\footer.html:51:30": execute of template failed: template: partials/footer.html:51:30: executing "partials/footer.html" at <$themeLogo.Resize>: error calling Resize: image "C:\\Users\\John\\Documents\\john-doe.github.io\\themes\\toha\\assets\\images\\theme-logo.png": open C:\Users\John\Documents\john-doe.github.io\resources\_gen\images\theme-logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png: Access is denied.
ERROR 2021/10/19 17:38:47 render of "page" failed: execute of template failed: template: notes/single.html:41:8: executing "notes/single.html" at <partial $footerTemplate .>: error calling partial: "C:\Users\John\Documents\john-doe.github.io\themes\toha\layouts\partials\footer.html:51:30": execute of template failed: template: partials/footer.html:51:30: executing "partials/footer.html" at <$themeLogo.Resize>: error calling Resize: image "C:\\Users\\John\\Documents\\john-doe.github.io\\themes\\toha\\assets\\images\\theme-logo.png": open C:\Users\John\Documents\john-doe.github.io\resources\_gen\images\theme-logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png: Access is denied.
ERROR 2021/10/19 17:38:47 render of "page" failed: execute of template failed: template: _default/search.html:41:8: executing "_default/search.html" at <partial $footerTemplate .>: error calling partial: "C:\Users\John\Documents\john-doe.github.io\themes\toha\layouts\partials\footer.html:51:30": execute of template failed: template: partials/footer.html:51:30: executing "partials/footer.html" at <$themeLogo.Resize>: error calling Resize: image "C:\\Users\\John\\Documents\\john-doe.github.io\\themes\\toha\\assets\\images\\theme-logo.png": open C:\Users\John\Documents\john-doe.github.io\resources\_gen\images\theme-logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png: Access is denied.
ERROR 2021/10/19 17:38:47 render of "page" failed: execute of template failed: template: notes/single.html:41:8: executing "notes/single.html" at <partial $footerTemplate .>: error calling partial: "C:\Users\John\Documents\john-doe.github.io\themes\toha\layouts\partials\footer.html:51:30": execute of template failed: template: partials/footer.html:51:30: executing "partials/footer.html" at <$themeLogo.Resize>: error calling Resize: image "C:\\Users\\John\\Documents\\john-doe.github.io\\themes\\toha\\assets\\images\\theme-logo.png": open C:\Users\John\Documents\john-doe.github.io\resources\_gen\images\theme-logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png: Access is denied.
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: notes/single.html:41:8: executing "notes/single.html" at <partial $footerTemplate .>: error calling partial: "C:\Users\John\Documents\john-doe.github.io\themes\toha\layouts\partials\footer.html:51:30": execute of template failed: template: partials/footer.html:51:30: executing "partials/footer.html" at <$themeLogo.Resize>: error calling Resize: image "C:\\Users\\John\\Documents\\john-doe.github.io\\themes\\toha\\assets\\images\\theme-logo.png": open C:\Users\John\Documents\john-doe.github.io\resources\_gen\images\theme-logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png: Access is denied.
Built in 1208 ms`

**Comment by pboling** [comment]
`git submodule add https://github.com/hossainemruz/toha.git themes/toha`

You are reporting this bug to `https://github.com/hugo-toha/toha`, not `github.com/hossainemruz/toha`.  Are you sure you are using the repo you think you are using?

**Comment by pboling** [comment]
@Chandler-Stewart It may also be due to file permissions?  What permissions are on the file that gets denied, e.g. `logo_hu8376fd15465fef26ffe66b6bcf0ca686_13669_32x0_resize_box_3.png`

**Comment by Chandler-Stewart** [comment]
I restarted, yet again. It was fixed and likely to your first point, thank you!
