### ISSUE TITLE
Uncaught reference error: adjustSkillCardsHeight() is not defined

### ISSUE THREAD

**Issue by Nirzak** [hugo-toha/toha#441]
## Expected Behavior

There should be a declaration for this function in home.js file.

## Current Behavior

But no function titled "adjustSkillCardsheight()" is defined. This might also cause other errors such as skill cards will not resize when reduce to mobile screen and etc. 
## Possible Solution

Either this function should be defined or be deleted if is not useful.

## Steps to Reproduce

1. Open https://hugo-toha.github.io
2. Press ctrl + shift + J to open the developer menu.
3. Click on the console tab

### Screenshots
![Screenshot (3793)](https://user-images.githubusercontent.com/11460645/138077929-63984bcb-e36c-4380-a3c9-69c194d5f071.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by pboling** [comment]
Having this same error.  Not sure when but my [toha themed site](https://railsbling.com) is now completely broken, and although I don't think it is related, this is the only error.

**Comment by hossainemruz** [comment]
@pboling It seems your website is looking for the CSS files in `https://railsbling.com/assets/css/layouts/` directory where they are available at `https://railsbling.com/css/layouts/` directory. I am not sure why.

**Comment by Nirzak** [comment]
> Having this same error. Not sure when but my [toha themed site](https://railsbling.com) is now completely broken, and although I don't think it is related, this is the only error.

I think you should update to the latest toha theme and also check the baseURL of your config.yaml file.

**Comment by pboling** [comment]
I had hard coded `assets/` into the source refs... not sure why.  The site is working again!

**Comment by t-muehlberger** [comment]
I am having the same issue, what happened to the implementation of the `adjustSkillCardsheight()` function? Can it be removed or will this cause a Bug?

**Comment by hossainemruz** [comment]
@t-muehlberger this functionality is now done by CSS. We removed the unnecessary `adjustSkillCardsheight()` function but forgot to remove the reference to it. Try pulling the latest `main`. This should be fixed in #488
