### ISSUE TITLE
Show less/more button not working because id conflict

### ISSUE THREAD

**Issue by hossainemruz** [hugo-toha/toha#457]
## Expected Behavior

Ref: https://lknespler.github.io/#education
![image](https://user-images.githubusercontent.com/12577390/139926052-2ebeb048-3471-4cfa-ae10-285ebd6dbd39.png)

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by fabiofenoglio** [comment]
https://github.com/hugo-toha/toha/pull/473 should have fixed this too

**Comment by hossainemruz** [comment]
Thank you again.
