### ISSUE TITLE
Feature Request: adding ko-fi floating button

### ISSUE THREAD

**Issue by kingabzpro** [hugo-toha/toha#463]
### Describe the solution you'd like
I want to add Ko-fi floating button: https://ko-fi.com/Manage/donation-widget-setup

### Describe alternatives you've considered
I am not good at web development.

### Additional context
I want to add this: 
```javascript
<script src='https://storage.ko-fi.com/cdn/scripts/overlay-widget.js'></script>
<script>
  kofiWidgetOverlay.draw('kingabzpro', {
    'type': 'floating-chat',
    'floating-chat.donateButton.text': 'Support me',
    'floating-chat.donateButton.background-color': '#5cb85c',
    'floating-chat.donateButton.text-color': '#fff'
  });
</script>
```

**Comment by hossainemruz** [comment]
Where do you want this button? In every page? Does it has to be a floating button? You can add a custom menu in the navbar. You can add the support button there. Will it meet your requirement?

**Comment by kingabzpro** [comment]
Yes floating button looks awesome, but for now can you explain how do i add support button on navbar?

**Comment by hossainemruz** [comment]
Just add `customMenus` in your `data/en/site.yaml` file.
Ref: https://github.com/hugo-toha/hugo-toha.github.io/blob/49a07c987c88fc01febdf268bd9cf217ae10e2c5/data/en/site.yaml#L14

**Comment by kingabzpro** [comment]
Thank you, It worked.

**Comment by hossainemruz** [comment]
You are welcomed. Can you please, close this issue now?

**Comment by kingabzpro** [comment]
Will you every add support for the donation or contribution button so that people can contribute? I mean its part of eco system.

**Comment by hossainemruz** [comment]
> Will you every add support for the donation or contribution button so that people can contribute? I mean its part of eco system.

We can do that. Reopening this as feature request.

**Comment by kingabzpro** [comment]
How do I add floating button? @hossainemruz

**Comment by hossainemruz** [comment]
Update theme to latest main branch. Then add this support section in your config.yaml.
https://github.com/hugo-toha/hugo-toha.github.io/blob/842e5f2fb6058adf7d3e75fe2378894518be22a1/config.yaml#L118

**Comment by kingabzpro** [comment]
Not working.

**Comment by hossainemruz** [comment]
Can you point me to your repository?

**Comment by kingabzpro** [comment]
I have given you collaborator access

**Comment by kingabzpro** [comment]
Thank you so much. I know its hard to read my toml😅
