### ISSUE TITLE
I want to use your theme in my blog post

### ISSUE THREAD

**Issue by kingabzpro** [hugo-toha/toha#464]
### Question
I want to use your theme in my blog post, do I have your permission to use your repository or code to explain how to create Data Science portfolio as non web developer?

**Comment by hossainemruz** [comment]
Sure. It's under MIT license. That's means you are free to use, modify, rebrand for any commercial or non-commercial purposes.

**Comment by MarionMoseby** [comment]
In fact @hossainemruz talking about modifications, I have seen @Javinator9889's toha and ¡I think its great! [See it here](https://www.javinator9889.com/), I think we might want to merge some of his improvements into upstream (I'll try)

**Comment by Javinator9889** [comment]
> In fact @hossainemruz talking about modifications, I have seen @Javinator9889's toha and ¡I think its great! [See it here](https://www.javinator9889.com/), I think we might want to merge some of his improvements into upstream (I'll try)

Please, do it @MarionMoseby! It would be awesome to have some of my changes at the base repository 😊

I think you can easily do a cherry pick of the commits you like and you will be ready to go!
