### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Anihilakos** [hugo-toha/toha#479]
Hi,
first of all thanks for the amazing and well put theme. I have created locally 2 additional fab-icons in footer.html, it would be great if you can add them on core. Please find the code below.

```
{{ else if (eq $key "tryhackme") }}
  <li><a href={{ printf "https://tryhackme.com/%s" $value }} target="_blank" rel="noopener">
    <span><i class="fab fa-tryhackme"></i></span> <span>{{ $value }}</span>
  </a></li>
{{ else if (eq $key "hackthebox") }}
  <li><a href={{ printf "https://www.hackthebox.com/%s" $value }} target="_blank" rel="noopener">
    <span><i class="fab fa-hackthebox"></i></span> <span>{{ $value }}</span>
```
 Thanks again and happy holidays,
 Iason

**Comment by hossainemruz** [comment]
Can you please explain why it is needed? How other users can benefit from it.

**Comment by Anihilakos** [comment]
I just thought more icons for everybody, but ok I understand these are for my use case mostly.
