### ISSUE TITLE
I can't get site.Params.background or anything in config.yaml parameters

### ISSUE THREAD

**Issue by nuhyurduseven** [hugo-toha/toha#480]
### Question

I can't get site.Params.background or anything in config.yaml parameters. I tried to do  for background and disabling newsletter  but both are not working.  I think it cannot read config.yaml. How can I fix it?

**Comment by hossainemruz** [comment]
Make sure you don't have both `config.yaml` and `config.toml` files. If you point me to your repository, I can take a look.

**Comment by nuhyurduseven** [comment]
Yes, I did  and done. Thank you.
