### ISSUE TITLE
Nav-Bar is not displayed correctly when using a link that contains a section

### ISSUE THREAD

**Issue by t-muehlberger** [hugo-toha/toha#485]
## Expected Behavior
When visiting the page via a link that references a section (such as [https://hugo-toha.github.io/#skills](https://hugo-toha.github.io/#skills)) the nav-bar should be displayed correctly as shown in below screenshot.

![Screenshot from 2022-01-02 19-55-44](https://user-images.githubusercontent.com/26621348/147886424-34c8b62d-6d45-44c1-964e-08db70aa0f7f.png)

## Current Behavior
The nav-bar is not displayed correclty. The current behavior is shown in below screenshot.

![Screenshot from 2022-01-02 19-55-24](https://user-images.githubusercontent.com/26621348/147886448-885498c6-8b9c-46e4-ba8f-674ea01e3817.png)

## Possible Solution

This code should be extracted in its own function and be called on page-load as well as on scroll (currently it is only called on scroll event)

https://github.com/hugo-toha/toha/blob/main/static/js/navbar.js#L11-L37

Please let me know if this would be an acceptable solution, in that case I will create a pull-request.

## Steps to Reproduce

Open this link  [https://hugo-toha.github.io/#skills](https://hugo-toha.github.io/#skills)

### Browsers Affected

Most likely all of them, tested in Firefox and Chromium.

**Comment by hossainemruz** [comment]
@t-muehlberger I can confirm the issue. It will be great if you can send a PR.
