### ISSUE TITLE
how can I make data/author.yaml multilingual?

### ISSUE THREAD

**Issue by stueja** [hugo-toha/toha#491]
### Question
I love the multilingual feature of toha. Unfortunately, I couldn't find a way to make the author information in data/author.yaml multilingual. (Neither data/english/author.yaml nor author.en.yaml, likewise other languages work).
How can I make the author information multilingual? 
Thanks alot.

**Comment by hossainemruz** [comment]
You have to put your data under respective language short code folder. For example, you have to put the English version of your data under `data/en` directory. Here, is an example: https://github.com/hugo-toha/hugo-toha.github.io/tree/source/data

You also have to set `languages` section in your `config.yaml` file. Here is an example: https://github.com/hugo-toha/hugo-toha.github.io/blob/9495ea8e80720286f63cda0d75e2dcc6ae0700f7/config.yaml#L9

**Comment by stueja** [comment]
First, thanks for the lightning fast answer. 
Then, it worked perfectly using `data/en` instead of `data/english`.
Thanks alot!
