### ISSUE TITLE
Language selector on mobile works only on second tap

### ISSUE THREAD

**Issue by stueja** [hugo-toha/toha#498]
## Expected Behavior
On a mobile phone or tablet, when tapping on the language in the language selector, the list of languages should appear.

## Current Behavior
When tapping onto the language selector, the meu closes. 

## Steps to Reproduce

1. On iPhone or iPad, open Safari or Firefox Mobile
2. open a toha webpage with at least two languages configured, e. g. hugo-toha.github.io
3. open the top right menu
4. tap on the language selector

### Browsers Affected

- [ ] Chrome
- [ x ] Firefox for iOS v 40
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ x ] Safari on iOS 15.0.2
- [ ] IE 11

**Comment by hossainemruz** [comment]
I can confirm the issue. Thanks for reporting.

**Comment by hossainemruz** [comment]
Try updating to v4 version. This should be fixed now. Feel free to re-open if the issue still persist after updating the theme to latest version.
