### ISSUE TITLE
bug--#493,will cause more to display the wrong number of items.

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#503]
## Expected Behavior

will cause more to display the wrong number of items.
#493 
## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

![QQ图片20220118124901](https://user-images.githubusercontent.com/29678677/149873741-7ac05242-0f12-4542-a1fd-8a09ae62777e.png)

**Comment by Chow-Ray** [comment]
@stueja @hossainemruz

**Comment by stueja** [comment]
@Chow-Ray , can you please be a little more specific in your bug report as what you expected and what happens? Thanks.

**Comment by hossainemruz** [comment]
I can confirm the issue. The solution is to start this counter from `1`.
Ref: https://github.com/hugo-toha/toha/blob/99a131fe438870d16891623bda3634befa372d70/layouts/partials/navigators/navbar.html?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L90

**Comment by hossainemruz** [comment]
Should be fixed by https://github.com/hugo-toha/toha/pull/509
