### ISSUE TITLE
Open Graphs does not work properly

### ISSUE THREAD

**Issue by salastro** [hugo-toha/toha#532]
When I add open graph section to `data/site.yaml` it does not work. I found that when moving it to `data/en/site.yaml` it works.
Additionally, the images points to a non-existing path for some reason. I have it to `/image/site/logo.jpg`, but the logo.jpg file is deleted in the final output.

**Comment by hossainemruz** [comment]
Yes. All the site data should be inside their language locale. You should also move your sections data under `en` folder.

Regarding the image, can you try putting `images/site/logo.jpg` instead of `/images/site/logo.jpg`?

**Comment by salastro** [comment]
> Regarding the image, can you try putting `images/site/logo.jpg` instead of `/images/site/logo.jpg`?

Yes, that worked. Thanks!
