### ISSUE TITLE
bug - When the tweet code appears in the article, it will cause the local rendering to fail.

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#563]
## Expected Behavior

When the tweet code appears in the article, it will cause the local rendering to fail.
```
### Tweet Sample

{{< tweet user="SanDiegoZoo" id="1453110110599868418" >}}

{{< vs >}}
```
log
```
 hugo server
Start building sites … 
hugo v0.95.0-9F2E76AF+extended windows/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
ERROR 2022/03/19 18:13:10 Failed to get JSON resource "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2FSanDiegoZoo%2Fstatus%2F1453110110599868418": Get "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2FSanDiegoZoo%2Fstatus%2F1453110110599868418": dial tcp 108.160.169.181:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Error: Error building site: logged 1 error(s)
Built in 21820 ms
```
## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
This format is deprecated in new version of hugo.
```
{{< tweet 1085870671291310081 >}}
```

**Comment by Chow-Ray** [comment]
I made a mistake before and used the following code. Like [hugo-toha.github.io](https://github.com/hugo-toha/hugo-toha.github.io/blob/842e5f2fb6058adf7d3e75fe2378894518be22a1/content/posts/category/sub-category/rich-content/index.md), the local rendering is wrong, but uploading to the server can generate webpages normally.
```
### Tweet Sample

{{< tweet user="SanDiegoZoo" id="1453110110599868418" >}}

{{< vs >}}
```

**Comment by hossainemruz** [comment]
Then, probably it was unable to get the tweet from local server. Don't look like it has anything to do with the theme. Can you please close the issue?

**Comment by Chow-Ray** [comment]
呵呵，fine。
