### ISSUE TITLE
Disabe TOC if there is no headings in the post

### ISSUE THREAD

**Issue by salastro** [hugo-toha/toha#574]
### Describe the solution you'd like

If there is no suitable headings in the post, then do not show the table of contents.

### Describe alternatives you've considered

Making it possible to disable in post configuration (`TOC: false` only for this post).

### Additional context

Sometimes, I write super simple stuff that does not need headings, so the TOC looks very annoying since it's completely empty

**Comment by hossainemruz** [comment]
We don't have any way to identify whether the page has heading or not when Hugo build the website. So, I think adding control in page level will be the way to go.
