### ISSUE TITLE
Browser crashes when accessing site with lots of posts

### ISSUE THREAD

**Issue by MarionMoseby** [hugo-toha/toha#577]
## Expected Behavior
The website should render OK

## Current Behavior
My personal website (http://localhost:1313/es/posts/) crashes when I access the "posts" section, at least since I added a ton of new posts. 

## Possible Solution
No idea, sorry

## Steps to Reproduce
1. Enter my website (both from Firefox and Chrome)
2. The browser crashes
(Maybe its just my computer?)

### Screenshots
![Screenshot_20220406_170639](https://user-images.githubusercontent.com/48572431/162006741-ab080108-7eea-43e8-88a2-2c32eb85c24c.png)

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description
Really what I said, the browser cannot run the page

**Comment by pboling** [comment]
Maybe you changed the name of that post, and it doesn't exist anymore?

**Comment by MarionMoseby** [comment]
Nono, its just that it is difficult for the browser to load too much data

**Comment by hossainemruz** [comment]
Updating theme to latest version may solve the issue. We have optimized resource loading. Feel free to re-open if the issue still persist.
