### ISSUE TITLE
Poor smooth scrolling to anchor tags in Firefox

### ISSUE THREAD

**Issue by dugite-code** [hugo-toha/toha#581]
## Expected Behavior
Scrolling to anchor tags in Firefox should be smooth like in Chromium based browsers

## Current Behavior
Scrolling to anchor tags in Firefox 99.1 is jerky with screen tearing.

## Possible Solution
Adding the smooth scrolling behavior to the css appears to fix this issue.

```
html {
  scroll-behavior: smooth;
}
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
We already have smooth scrolling support. Please, update to latest version and check if the issue persist. Feel free to re-open if the issue still persist.
