### ISSUE TITLE
Bug in New Blog Post - time showing as variable, not actual Time

### ISSUE THREAD

**Issue by tom-iteverything** [hugo-toha/toha#587]
## Expected Behavior
When creating a new post, the date should be presented below the Avatar of the author.

## Current Behavior
It is providing code instead of the date: `:date_full`

## Possible Solution
Correct the code within:
[toha/layouts/_default/single.html](https://github.com/hugo-toha/toha/blob/main/layouts/_default/single.html)
**Line 51** 

## Steps to Reproduce
1. Create blog post via markdown file
2. Date shows incorrectly

### Screenshots
https://imgur.com/a/yfH3VTH

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description
It appears that **Line 51** is not finished with the referencing of `:date_full`... perhaps a `:` is missing at the end or the line in general is mistyped?  Prior versions had the following:
`<p>{{ .Page.Date.Format "January 2, 2006" }}</p>`
Current version has:
`<p>{{ .Page.Date | time.Format ":date_full" }}</p>`
Possible fix:
`<p>{{ .Page.Date | time.Format ":date_full:" }}</p>`

**Comment by hossainemruz** [comment]
Update your Hugo version. This variable has been introduced in recent hugo version.

**Comment by tom-iteverything** [comment]
> Update your Hugo version. This variable has been introduced in recent hugo version.

ah - thank you so much!  deeper issue found then since my `netlify.toml` wasn't playing nice deploying the most recent version.  this resolved it!

thank you kindly!
