### ISSUE TITLE
How can I get the Hugo default gist shortcode rendering?

### ISSUE THREAD

**Issue by quantitative-technologies** [hugo-toha/toha#599]
### Question

Using the gist shortcode with this theme give me undesirable output. There is so much extra space around each line that it is difficult to read (e.g. cannot see much on one screen). Here is a [snapshot](https://pasteboard.co/DUMrPngAkjfT.png):

How can I get the default gist shortcode rendering?

**Comment by hossainemruz** [comment]
We probably need to fix the CSS.

**Comment by quantitative-technologies** [comment]
Do you have any idea which file that is? I tried commenting out the `codeblocks` section in `main.css` but it had no effect.

**Comment by hossainemruz** [comment]
I have to check the generated HTML. This is Hugo's internal shortcode. I have to check the classes it produces.

**Comment by hossainemruz** [comment]
Hi @quantitative-technologies! Fixed in #606. Please, pull the latest changes.

**Comment by quantitative-technologies** [comment]
Perfect!
