### ISSUE TITLE
images links broken when hugo is served from a sub-folder 

### ISSUE THREAD

**Issue by shoaibb** [hugo-toha/toha#604]
## Expected Behavior
The links to images (such as background img) should be consistent even if there is a sub-dir instead of main dir in the config.yaml file.

## Current Behavior
When baseurl is set to https://user.github.io/toha instead of https://user.github.io/ or / , the site does not load background image even the default ones. 

## Steps to Reproduce

1. changed baseurl from user.github.io to user.github.io/toha
2. followed rest of the instruction from https://toha-guides.netlify.app/posts/getting-started/prepare-site/ 
3. when hugo serve command is invoked, the background image does not appear
4. added background: /images/default-background.jpg as well to config.yaml but still no success.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Can you please inspect the HTML and check what is the URL is set for the background image?

**Comment by shoaibb** [comment]
@hossainemruz The generated html has this following link to background image:

`background-image: url('https://username.github.io/toha/toha/images/default-background.jpg');`

**Comment by shoaibb** [comment]
@hossainemruz sure, here it is: https://github.com/shoaibb/src_toha

When I serve this repo locally, I do not get a correct link to images including background. Probably this is also causing a problem when I try Github Actions to serve the code in this repo but that's another issue and might be resolved if the images url are fixed.

**Comment by hossainemruz** [comment]
@shoaibb It was bug in the theme. I have fixed it in #605. Please, pull the latest changes.
