### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by enzobercasio** [hugo-toha/toha#607]
## Expected Behavior
successful build after running hugo command

## Current Behavior
error: Error: Error building site: "/codebuild/output/src170754315/src/content/notes/bash/basic/index.md:13:1": failed to extract shortcode: template for shortcode "note" not found

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Can you check your `themes/toha` folder? Is there any files or it just redirect to original theme repo?

**Comment by enzobercasio** [comment]
there are files in the themes/toha. I get the same error on my forked repo without any changes or direct clone from the original repo without any changes.

**Comment by hossainemruz** [comment]
Can you share your repo so I can check?

**Comment by enzobercasio** [comment]
https://github.com/enzobercasio/ebercs-blog-2

**Comment by hossainemruz** [comment]
When you have cloned the repo, the theme wasn't pulled. Use `--recursive` flag with `git clone` command.

**Comment by enzobercasio** [comment]
it is working now on the forked repo but in my other repo (https://github.com/enzobercasio/enzobercasio), it works on my local but when I run it in my CodePipeline in AWS, I am getting the same error. (see [buildspec.yaml](https://github.com/enzobercasio/enzobercasio/blob/main/buildspec.yaml))

**Comment by enzobercasio** [comment]
sorry, it is my buildspec.yaml error. I missed to cd to the directory. it is fixed now.

**Comment by hossainemruz** [comment]
Cool. Can you please close this issue now?
