### ISSUE TITLE
[Feature Request] 'Curriculum Vitae' button instead of the 'Resume' button

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#610]
Hello folks,

This is a very minor feature request, which would be very helpful for researchers.
The current website has a link for one's resume. It would be cool if we can use the word 'Curriculum Vitae' instead of 'Resume' for those in academia.

Thank you.

**Comment by hossainemruz** [comment]
We can not change the button text for all but we can make it configurable.

**Comment by IhnwhiHeo** [comment]
Would be great if it can be configurable (if it means the word can be changed)! Could you please consider this?

**Comment by hossainemruz** [comment]
Yes. Will try to do in this weekend.

**Comment by IhnwhiHeo** [comment]
Thank you!

**Comment by hossainemruz** [comment]
@IhnwhiHeo added in #611
