### ISSUE TITLE
Why do I get a display error when creating a new page?

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#614]
### Question

Why do I get a display error when creating a new page?
https://chowray.netlify.app/about/
![QQ截图20220717213329](https://user-images.githubusercontent.com/29678677/179400895-4f7d2240-4cfc-411f-be3f-96b9e5fc77b7.jpg)

**Comment by hossainemruz** [comment]
I am suspecting that it is not applying the CSS.

**Comment by Chow-Ray** [comment]
> I am suspecting that it is not applying the CSS.

So how to solve this problem?

**Comment by hossainemruz** [comment]
I don't know. If you share your repo, I may be able to check.

**Comment by hossainemruz** [comment]
Feel free to reopen if you still facing this issue.
