### ISSUE TITLE
Appearance problem with ko-fi button and dark theme

### ISSUE THREAD

**Issue by FunctionalHacker** [hugo-toha/toha#615]
## Expected Behavior

The button should render correctly
## Current Behavior

This button has an extra rectangular white background.

## Possible Solution

This is obviously related to either the recent dark theme implementation in Toha, or the ko-fi integration but I have not looked into it more specifically.

## Steps to Reproduce

1. Navigate to a page using Hugo Toha theme
2. Change to the dark theme if not already set
3. Reload the page if you had to change from the light theme to the dark theme
4. Now you should see the result like my screenshot below

### Screenshots

![image](https://user-images.githubusercontent.com/16839187/179726402-f7c6c04c-e4f5-4547-8761-3fc52bf762ba.png)
~~Can be tested on my site at  [korhonen.cc](https://korhonen.cc)~~ Ko-fi button not available anymore

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge (not tested)
- [ ] Safari 11 (not tested)
- [ ] Safari 10 (not tested)
- [ ] IE 11 (not tested

**Comment by hossainemruz** [comment]
Don't see Ko-fi button on your site.

**Comment by FunctionalHacker** [comment]
Sorry, I just looked into the law in my country and apparently it is not legal to collect money here, so I had to remove it. Can we perhaps add a button to the demo site of Toha? I don't know if a dummy account would work though.

**Comment by hossainemruz** [comment]
Ok. I will check.

**Comment by MarionMoseby** [comment]
You may reproduce this error in my site: https://www.pablomarcos.me/
Codeberg repo: https://codeberg.org/FlyingFlamingo/pablomarcos-me

**Comment by hossainemruz** [comment]
Looks fine to me.
![image](https://user-images.githubusercontent.com/12577390/183336525-ddd18375-0c56-4e49-84fd-d987206b2e48.png)

**Comment by MarionMoseby** [comment]
Hum! Weird. Could you try on Firefox?

------- Original Message -------

**Comment by FunctionalHacker** [comment]
![Screenshot_20220808-133840_Fennec](https://user-images.githubusercontent.com/16839187/183399870-78fd387a-f339-4856-b2ee-9a930dda93fc.png)
I forced the dark theme from the menu and was able to reproduce it on Firefox Android.

Can't seem to reproduce using a Chromium based browser (FOSS Browser)

**Comment by FunctionalHacker** [comment]
Btw on Firefox Android, if I leave the website theme on auto and change my phone theme to dark, the dark theme seems to work properly even after page reloads.

**Comment by hossainemruz** [comment]
Look like something is broken. Lot's of error log. I have to take a look.
![image](https://user-images.githubusercontent.com/12577390/183414342-b3a5fd0a-3492-4a47-ad18-f114290c06c8.png)

**Comment by Yomisana** [comment]
Any progress on this?
Sometimes change to dark mode will not show up white block but console still have that error log.

**Comment by hossainemruz** [comment]
Hi @Yomisana. Sorry to disappoint. Not getting time to work on this issue. Going through some tough time.
