### ISSUE TITLE
Would you consider using "zh-Hans" and "zh-Hant" instead of "zh-cn" and "zh-tw"?

### ISSUE THREAD

**Issue by misitebao** [hugo-toha/toha#618]
### Question

"zh-cn" and "zh-tw" do not accurately reflect the branches of Chinese, because there are many other regions that use Chinese, and more accurate descriptions for these two should be "zh-Hans" and "zh-Hant".

(It's a bit of a shame that Hugo currently enforces lowercase language codes in URLs.😖)

If such a need can be approved, I'd be happy to contribute a PR for it.

**Comment by hossainemruz** [comment]
Hi @misitebao, "zh-cn" and "zh-tw" is seems to be widely used. So, I think we should stick with that.

**Comment by misitebao** [comment]
@hossainemruz 
OK, I see, thanks for the reply.
