### ISSUE TITLE
customizeable experience.yaml and markdown inside yaml

### ISSUE THREAD

**Issue by HabibRh26** [hugo-toha/toha#62]
I tried to add an extra key in experience.yaml file but it is not working. Could you tell me how can I add it?. I don't want to follow your points in this file. Is there any way of using markdown syntax inside the yaml key values?

**Comment by hossainemruz** [comment]
What additional points you want to user? You might need to customize underlying experience template.

**Comment by HabibRh26** [comment]
@hossainemruz vai, I want to remove the lists type texts that you used in yaml and want to use a lot of textual sentences and lists in yaml and want to define my own customized key in yaml.

**Comment by alex-bezek** [comment]
Hey @HabibRh26 ,

>  want to remove the lists type texts that you used in yaml and want to use a lot of textual sentences and lists in yaml and want to define my own customized key in yaml. 

I don't think I quite follow what you are trying to accomplish. Could you possibly provide screenshots or links/examples of the code you want to change? 

> How can I edit the underlying exp template?

If you are trying to heavily change how the theme works, this may be the right answer. You can copy it and override it by doing this https://bwaycer.github.io/hugo_tutorial.hugo/themes/customizing/ .

If you are just trying to add additional optional functionality to the section, a mockup + example yml config would be really helpful to visualize what you're trying to do. Thanks!

**Comment by hossainemruz** [comment]
This will probably need a customized template. Closing the issue because of inactivity.
