### ISSUE TITLE
Feature Request: url in achievement section 

### ISSUE THREAD

**Issue by mangla-sarvesh** [hugo-toha/toha#621]
### Describe the solution you'd like

achievements:
- title: Best Poster Award Winner
  **url: "https://example.com"**
  image: /images/sections/achievements/git.png
  summary: Best presenter in the 2020 XYZ conference.

**_can url be added. sometimes the award are available in the website, so anybody can see the authancity of the award._**

**Comment by hossainemruz** [comment]
Sure

**Comment by hossainemruz** [comment]
If you provide url in a achievement entry, the `Details` button will show up. Does it meet your requirement?

![image](https://user-images.githubusercontent.com/12577390/181811285-5c45b27d-25c5-4d93-a6a6-08056528b424.png)

**Comment by mangla-sarvesh** [comment]
Great. Working Fine now
