### ISSUE TITLE
Enable "Recent posts" for a different language

### ISSUE THREAD

**Issue by MarionMoseby** [hugo-toha/toha#625]
### Describe the solution you'd like

I currently use the Spanish version of my blog as its "main" or "international" version, since I dont want to go through the effort of translating all my posts. This means that, when I implement the "Recent Posts" function, only the posts in the current language appear, which looks super updated. I would like to have a lenguage switch in _recent-posts.yaml_ so as to choose from which lang I want the Recent Posts thing generated.

### Describe alternatives you've considered

Cant think of any

### Additional context

If authorized, I am willing to implement this myself

**Comment by hossainemruz** [comment]
Sure. Go on.
