### ISSUE TITLE
Dark mode changes the image color for post card

### ISSUE THREAD

**Issue by LalithKumar010** [hugo-toha/toha#627]
## Expected Behavior

The pic should remain same in the post in both light and dark modes

## Current Behavior

The hero pic of a post is loosing its color when changing from light mode to dark mode

## Steps to Reproduce

1. Create a post with a hero.svg photo
2. Enable dark and light modes in your blog
3. Change from light mode to dark mode
4. See the recent posts section

### Screenshots

bug in dark mode
![image](https://user-images.githubusercontent.com/90268212/183608021-eedfaae0-3064-42ad-a3ab-0071d86ca2d4.png)
Original pic in light mode
![image](https://user-images.githubusercontent.com/90268212/183608027-fff1f840-7bdd-4fd4-8528-c1282ccf52a4.png)

### Browsers Affected

- [] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

When we are changing to dark mode from light mode in firefox the pic is changing / loosing  its colours

**Comment by hossainemruz** [comment]
I can confirm the issue.
