### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LalithKumar010** [hugo-toha/toha#628]
## Expected Behavior

Should be able to view the thumbnail of the post
## Current Behavior

Alternate text of the pic being displayed instead of the pic
## Steps to Reproduce

1. Open your recent posts and posts section in chrome
2.
3.
4.

### Screenshots

In chrome
![image](https://user-images.githubusercontent.com/90268212/183609018-9ed4812e-87c1-4878-91c7-9107525431b2.png)
![image](https://user-images.githubusercontent.com/90268212/183609077-296bc07e-4e70-47ee-9a9e-771c2cca8a4e.png)
In firefox it is working well
![image](https://user-images.githubusercontent.com/90268212/183609157-89d8a146-5534-47cf-9d4e-46c709f3057b.png)
![image](https://user-images.githubusercontent.com/90268212/183609190-5c65e12a-8e48-4326-87e5-ddc028105a12.png)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by LalithKumar010** [comment]
All chromium based browsers are effected don't know why

**Comment by hossainemruz** [comment]
Suspecting the issue is with the SVG image.
![image](https://user-images.githubusercontent.com/12577390/183615467-c7d5ebf8-57c8-441f-a47f-cff31f324708.png)

**Comment by LalithKumar010** [comment]
Is there any way to add jpg files instead of SVG ?

**Comment by hossainemruz** [comment]
Yes.
