### ISSUE TITLE
Is there a way to not use Google fonts and add privacy policy?

### ISSUE THREAD

**Issue by Beluguy** [hugo-toha/toha#630]
### Question
I would like to use a different font system other than Google fonts, partly due to privacy reasons and to be compliant with privacy laws. According to Cookiebot.com, my implementation of the theme is not compliant with ePrivacy Directive (ePR).  Is it also possible to add a dedicated privacy policy and copyright disclaimer? Thanks for the amazing theme! 👍

**Comment by MarionMoseby** [comment]
We should actually try to serve this locally I think
