### ISSUE TITLE
Use CSS custom properties (variables) for template colours

### ISSUE THREAD

**Issue by daviddavo** [hugo-toha/toha#634]
### Describe the solution you'd like

The colour definition is repeated a lot of times in a lot of files, which makes it difficult for users of the template to change the colour palette.

Instead of repeating `#1C2D41` 11 times, we could use `color: var(--color-heading)`. This variable would be defined in the body, like this:

```css
body {
  --color-heading: #1C2D41;
}
```

Then, if the user wants to change the colour palette, they could override the `--color-heading` property in body, by modifying the `style.css` file.

```css
body {
  --color-heading: red;
}
```

If this style is loaded after the one where we define the colours, the cascading style sheet will apply this colour instead to every item that uses that variable.

Furthermore, I think that these colour definitions should be in a new css file, called `colors.css` or something like that. That way, you could override that file instead of defining it on `style.css` (less space consumed).

### Describe alternatives you've considered

Overriding manually every item that uses a theme coulour in my webpage.

### Additional context

- [Using CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

If there's interest in this, I wouldn't mind making a PR myself. Feel free to assign it to me.

**Comment by hossainemruz** [comment]
Sound like a good idea. Didn't knew it is possible. Would you like to go ahead and send a PR?

**Comment by daviddavo** [comment]
I've been doing this for some colours in my own branch, the thing is, I don't know what to name the colours.

The main ones are easy because they were already named: heading, paragraph, iconography, secondary, dirty snow, snow...

The problem is that there are a lot of "unnamed" colours, like [#248aaa](https://github.com/hugo-toha/toha/search?q=%22%23248aaa%22&type=).

Should I name the variable `--color-link` because it's used for anchors? But it is also used sometimes as a border. Should I split it in two variables? Maybe multiple things having the same colour was just a coincidence...

There are a lot of questions to be solved before getting into it "seriously". I started doing it in my own branch using regex substitutions, without taking much into consideration, but I think it's a good example on how it will end up being used:

- [themes/toha/static/css/colors.css](https://github.com/daviddavo/toha/blob/css-var-colours/static/css/colors.css) (Current colour scheme)
- [static/css/style.css](https://github.com/daviddavo/daviddavo.github.io/blob/5520b28b99fc54e71b70e81aba903405d2763eb8/static/css/style.css) (Colour scheme modified by user)
- https://cf9aa96e.daviddavo.pages.dev/es/ (Deployed page with modified colour scheme)

If a color is just "main blue, but 20% darker", this colour could also be defined using something like [SASS/SCSS](https://gohugo.io/hugo-pipes/scss-sass/), or with CSS filters, that way the user would have to change less variables.

Is there any documentation on how the colours were chosen? If not, we should really create one before starting this.

**Comment by hossainemruz** [comment]
Hmm... We have to decide which color will be used for which purpose and name them accordingly. Let me defines the colors. I will get back to this issue in few days.

**Comment by hossainemruz** [comment]
Color variables has been introduced in #785.
