### ISSUE TITLE
Support color purple for about soft skill circles

### ISSUE THREAD

**Issue by wickenico** [hugo-toha/toha#637]
Hi,  
I want to add Kotlin to my soft skills. The color of Kotlin Logo and themes about the language are purple, so I would love to use a purple circle. 
Could you integrate this color? 

Thanks a lot!

Regards,
Nico

**Comment by hossainemruz** [comment]
You can directly put a HEX color code in the color field. Here is an example:
https://github.com/hugo-toha/hugo-toha.github.io/blob/81fd689f36d77f2d6f77a10a7e1a6f4c0d867c29/data/en/sections/about.yaml#L95

**Comment by wickenico** [comment]
Thanks perfect! :)
