### ISSUE TITLE
Can't build site.

### ISSUE THREAD

**Issue by DipeshAggarwal** [hugo-toha/toha#646]
## Expected Behavior
The website should build.
EDIT: I have even tried following the instructions in https://toha-guides.netlify.app/posts/getting-started/prepare-site/
As soon as I create the sections folder, the build crashes.

## Current Behavior
Website build fails with

```
Error: Error building site: failed to render pages: render of "home" failed: "themes\toha\layouts\index.html:58:18": execute of template failed: template: index.html:58:18: executing "index.html" at <partial (printf "sections/%s.html" (replace (lower .section.id) " " "-")) .>: error calling partial: partial "sections/.html" not found
Built in 191 ms
```

Hugo version: `hugo v0.102.1-e9c3ce16abc391ee5be38f88b0499d0e8e19104c+extended windows/amd64 BuildDate=2022-08-29T12:58:13Z VendorInfo=gohugoio`

When I manually add a `.html` file in the partials/sections/ folder, the website builds but renders as an empty white page.

## Possible Solution
Have no idea what could be causing this bug.

### Screenshots
![Screenshot 2022-09-08 235633](https://user-images.githubusercontent.com/1311129/189198158-002aeafc-12ad-4531-bc0e-5303d1a5a6d3.png)
Files in my sections folder.

![Screenshot 2022-09-09 001647](https://user-images.githubusercontent.com/1311129/189201809-79b07734-3acc-49e9-801c-c5c5d4d867f3.png)
Crash screenshot.

### Browsers Affected
Not applicable since can't build site.

## Detailed Description
The build works perfectly fine on an older version of Toha (the one that released sometimes in late 2020). It's when I update it to the latest version that I'm seeing this issue.
From as far as I can tell, hugo is searching for a `.html` file and crashing when it is not finding it.

**Comment by hossainemruz** [comment]
Can you please share your repo so that I can take a look . Look like a configuration i.

**Comment by DipeshAggarwal** [comment]
Using all the default files from https://toha-guides.netlify.app/posts/getting-started/prepare-site/ seems to make it work. Will test more and report back if I see this issue pop up again.

**Comment by DipeshAggarwal** [comment]
Actually now after the first build, the website renders to an empty white page.

https://github.com/DipeshAggarwal/hugo-toha-test

Please take a look.
