### ISSUE TITLE
In dark mode, pages load in light mode briefly causing flashing

### ISSUE THREAD

**Issue by filcuk** [hugo-toha/toha#665]
## Expected Behavior
Pages should load in dark mode.

## Current Behavior
Pages load in light mode causing a bright flicker every time user navigates to a different page.

## Steps to Reproduce

1. Can be tested on https://hugo-toha.github.io/
2. Enable dark mode (or auto if applicable)
3. Navigate to 'Posts'
4. You should already see the effect, if not click around the navigation

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

Not tested:
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

If possible, change the theming so that dark or light mode apply on page load and not after.

**Comment by hossainemruz** [comment]
I can confirm the behavior.
