### ISSUE TITLE
Build probem on netlify

### ISSUE THREAD

**Issue by xsFactor** [hugo-toha/toha#667]
When deploying the template on netlify with the following step: [Deploy site in Netlify](https://toha-guides.netlify.app/posts/getting-started/netlify/) is unable to build

### **SHOWING THE FOLLOWING ERROR**

**2:35:38 AM:   1. build.command from netlify.toml**                            
 ​
2:35:38 AM: $ hugo --gc --minify
2:35:38 AM: Error: module "toha" not found; either add it as a Hugo Module or store it in "/opt/build/repo/themes".: module does not exist

**2:35:38 AM:   "build.command" failed**                                        
 ​
2:35:38 AM:   Error message
2:35:38 AM:   Command failed with exit code 255: hugo --gc --minify (https://ntl.fyi/exit-code-255)
2:35:38 AM: ​
2:35:38 AM:   Error location
2:35:38 AM:   In build.command from netlify.toml:
2:35:38 AM:   hugo --gc --minify
2:35:38 AM: ​
2:35:38 AM:   Resolved config
2:35:38 AM:   build:
2:35:38 AM:     command: hugo --gc --minify
2:35:38 AM:     commandOrigin: config
2:35:38 AM:     environment:
2:35:38 AM:       - HUGO_ENABLEGITINFO
2:35:38 AM:       - HUGO_ENV
2:35:38 AM:       - HUGO_THEME
2:35:38 AM:       - HUGO_VERSION
2:35:38 AM:     publish: /opt/build/repo/public
2:35:38 AM:     publishOrigin: config

2:35:39 AM: Build failed due to a user error: Build script returned non-zero exit code: 2

2:35:40 AM: Failing build: Failed to build site
2:35:40 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)

**Comment by hossainemruz** [comment]
Can you please try upgrading Hugo version? Here, is an sample:
https://github.com/hugo-toha/hugo-toha.github.io/blob/main/netlify.toml
