### ISSUE TITLE
CounterDev analytics not working

### ISSUE THREAD

**Issue by SrNetoChan** [hugo-toha/toha#668]
## Expected Behavior

I have configured counterDev but the site don't seem to be able to track anything from my visits to the site.

counterDev seems to expect a very simple string like

<script src="https://cdn.counter.dev/script.js" data-id="my_key" data-utcoffset="1"></script>

But the generate code is much more complex, like:

<script>!sessionStorage.getItem("_swa")&&document.referrer.indexOf(location.protocol+"//"+location.host)!==0&&fetch("https://counter.dev/track?"+new URLSearchParams({referrer:document.referrer,screen:screen.width+"x"+screen.height,user:"mykey",utcoffset:"1"})),sessionStorage.setItem("_swa","1")</script>

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Thank you @SrNetoChan for reporting the issue. I will take a look.

**Comment by SrNetoChan** [comment]
If it is of any helps, my site is www.aneto.pt

**Comment by hossainemruz** [comment]
@SrNetoChan Look like counter.dev has changed how the tracker is included in the site. This PR should fix the issue: #674.

Please update your theme to the latest commit and  let me know if it fixes the issue.

**Comment by SrNetoChan** [comment]
That was my thinking. But I wasn't sure if you were just doing it in another way.

Thanks for the fix!
