### ISSUE TITLE
"Publications" not working

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#671]
Hi folks!

I do like this theme a lot and recently tried to add the Publications section. However, the deployment did not work. Can you please check my code at https://github.com/IhnwhiHeo/ihnwhiheo.github.io/commit/d50d9c087f034ef297e089de6a834def4894eecc?

Thanks in advance.

**Comment by hossainemruz** [comment]
Hi @IhnwhiHeo, you are using an old version of theme. You are using theme version from July 16. Publication feature was added in July 29. That's why it's not working. Please update the theme.
Try doing: `git submodule update --remote`

**Comment by IhnwhiHeo** [comment]
Hi @hossainemruz,
Thanks for your reply. Now it works perfectly after the update :)
