### ISSUE TITLE
How to control navbar "collapsing"?

### ISSUE THREAD

**Issue by quantitative-technologies** [hugo-toha/toha#677]
On some browsers my webpage is collapsing the navbar into the 3 horizontal lines in the top-right corner, even though there is plenty of room for the section headings, since I currently only have 3 of them.

On my linux system, the webpage displays the sections as I would like:
![website-good](https://user-images.githubusercontent.com/29150871/197437120-e527ddc3-36f2-4d98-bc54-db4c29855c67.png)

However, on other OSes, for example on Windows Edge, the navbar is collapsed:
![website-collapsed](https://user-images.githubusercontent.com/29150871/197437275-2e03cfc7-e23b-4192-a685-f644f28041e1.png)

This was also reported by a user using a Mac, who also did not realize the website had any content!

Is there a way I can control this? Can the collapse be disabled completely? Though, this is not ideal because it probably should collapse when viewed on a mobile phone.

In the `navbar.html` layout file I see a setting `$maxVisibleSections`, but I'm not sure if this is relevant (or how to set it in the config either).

**Comment by hossainemruz** [comment]
HI @quantitative-technologies `$maxVisibleSections` has nothing to do with the navbar collapsing. The site is probably detecting the device as tablet. Can you please share your website link so that I can check if there is any other issues.

**Comment by quantitative-technologies** [comment]
Hi @hossainemruz

Please notice that this also happens on the Toha example site when I use Windows Edge (it's running in a VM if that is relevant):
![toha-website-collapsed](https://user-images.githubusercontent.com/29150871/197529644-689181ca-7de7-49bb-aa49-39dce84f1855.png)

But Toha has 9 or 10 section headings...

Here is the link to [my website](https://quantitative-technologies.com/).

**Comment by hossainemruz** [comment]
Hi @quantitative-technologies, this is expected behavior. If the device width is less or equal to `1024px`, then navbar goes into this mode. This is being handled by bootstrap framework itself.

**Comment by quantitative-technologies** [comment]
Yes, the Windows VM is 1024x768. I'm surprised if that was the case for the Mac too.

So how can I change the expected behaviour? I looked through the navbar code, and I don't see any reference to bootstrap. There must be some way to disable the bootstrap for just the navbar, or am I mistaken?

**Comment by hossainemruz** [comment]
If you inspect the code and check the CSS for`navbar-toggler` button, you will see it is disabled only for screen >= 1200px. Maybe, you can overwrite this behavior by setting media query for the the `navbar-toggler` button and the respective menu list. You might need to use important (`!`) sign to overwrite the bootstrap behavior.
![Screenshot from 2022-10-25 18-44-43](https://user-images.githubusercontent.com/12577390/197776674-7c9c1427-c9bf-4858-9186-99f573b72043.png)
