### ISSUE TITLE
Category filter for skills

### ISSUE THREAD

**Issue by kszpieg** [hugo-toha/toha#701]
### Describe the solution you'd like

Hi!

Have you considered adding a category filter for skills too? I saw on some portfolios that authors put his skills into categories like "Programming languages", "Frameworks", etc. I think that it can be helpful in this case.

### Describe alternatives you've considered

The same feature in projects works very well IMO. Maybe adapting it to skills will be enough?

**Comment by kszpieg** [comment]
Ah, I see that in #475 this idea is in some kind of preparation :D Didn't see this PR before creating the issue/feature request.

**Comment by hossainemruz** [comment]
I do have plan for it. However, it will take time. Don't hold your breath for it.
