### ISSUE TITLE
Dropdown Button for Blog Post Categories

### ISSUE THREAD

**Issue by luke-taylor** [hugo-toha/toha#708]
Firstly, I would like to say what a fantastic theme this is and complement anyone who has contributed so far.

## Current Issue
As far as I can tell, there is no feature that will allow me to simultaneously:
1. Stay on my current 'Post' page. 
2. View other 'Post' pages within a different category than the current one. 

![image](https://user-images.githubusercontent.com/77284962/202904944-f543d6c9-b09f-4446-9bfa-f6495ee12963.png)

In order to view the contents of '_Category_' I must click directly on the page 'Category' then the contents collapse and I can see the available pages. 

## Feature Proposal
Instead of having to click on the page '_Category_' it would be better if there was a button (such as the one located on the _Nav Bar_) that will allow me to view all the contents of '_Category_' without having to move from my current page of viewing. Similarly, for '_Sub-Category_'.

I think from a practicality standpoint, it's useful since you may not want to lose the page you're on but be curious to what posts are in other sections. 

## Personal Progress 
I have attempted to modify the `sidebar.html` and the `sidebar.css` files to match that of the buttons in the _Nav Bar_ that work in a similar manner, but my skills are a little too raw in this area, so any help would also be appreciated.

Thanks,
Luke

**Comment by hossainemruz** [comment]
You want to be able to expand a category without moving to the page? That would require to change how the menus are built. Certainly, doable but I don't think I have bandwidth to work on it.

**Comment by lukesmoak98** [comment]
That's fine, any ideas on where one my start if they were to attempt this?

**Comment by hossainemruz** [comment]
You have to make this `li` to an accordion.
https://github.com/hugo-toha/toha/blob/6704952afa1983f4583f3c3a431a2ae571d972bc/layouts/partials/navigators/sidebar.html#L11

You can check this bootstrap accordion example:
https://getbootstrap.com/docs/5.2/components/accordion/

**Comment by lukesmoak98** [comment]
Thanks! Do any further amendments need making, for example the `.css` file or making a new `.js` file?

**Comment by hossainemruz** [comment]
CSS and JS change may require.
