### ISSUE TITLE
Bug: Changing .background in home.css has no effect in Firefox

### ISSUE THREAD

**Issue by luke-taylor** [hugo-toha/toha#709]
## Versions 
Firefox: 107.0
Toha: v3.8.0
Hugo: v0.105.0

## Expected Behavior
Updating the `.background' block in sections/home.css should result in changes in the **Firefox** browser. 

## Current Behavior
Modifying this block (even discarding it entirely) has no effect.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Try following this new guideline. Feel free to re-open if the issue still persist.
https://toha-guides.netlify.app/posts/customizing/customize-css/
