### ISSUE TITLE
Cannot run website

### ISSUE THREAD

**Issue by salastro** [hugo-toha/toha#729]
## Expected Behavior
Everything runs nicely and I get normal hugo logs

## Current Behavior
```
➜  hugo server                                                                                    in hugo-toha.github.io on  main [!] is 📦 v0.1.0 via 🐹 v1.19.4 via 
Start building sites …
hugo v0.109.0+extended linux/amd64 BuildDate=unknown
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/application.js:2:7": Could not resolve "bootstrap"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/application.js:3:7": Could not resolve "@fortawesome/fontawesome-free/js/all"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/features/darkmode/darkreader.js:1:54": Could not resolve "darkreader"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/features/syntaxhighlight/hljs.js:1:17": Could not resolve "highlight.js"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/features/videoplayer/plyr.js:1:17": Could not resolve "plyr"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/pages/home.js:1:21": Could not resolve "ityped"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/pages/note.js:1:25": Could not resolve "imagesloaded"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/pages/search.js:1:17": Could not resolve "fuse.js"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/pages/search.js:2:17": Could not resolve "mark.js"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/sections/projects.js:1:22": Could not resolve "filterizr"
ERROR 2023/01/15 09:25:04 js.Build failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/sections/publications.js:1:22": Could not resolve "filterizr"
Error: Error building site: JSBUILD: failed to transform "scripts/application.js" (text/javascript): "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20230105191255-374b4019d89d/assets/scripts/application.js:1:7": Could not resolve "popper.js"
Built in 596 ms
```

## Steps to Reproduce

1. `git clone https://github.com/hugo-toha/hugo-toha.github.io.git`
2. `cd hugo-toha.github.io`
3. `hugo server`

## Detailed Description
* hugo **v0.109.0+extended linux/amd64** BuildDate=unknown
* **Void Linux x86_64** with **Linux 6.1.4_1** on **Inspiron 3521 A07** 
* Tried it on: 
    * my own website 
    * the default toha website

**Comment by salastro** [comment]
Oh, just found #725. I think it should be clarified. Like an issue that says the website is being rewritten should be pinned or it should be added to the `README`. Sorry for the annoyance and sorry again if it is already clearly written somewhere. I could not see it anywhere. I apologize again for wasting your time.

**Comment by hossainemruz** [comment]
Added a warning in the README. Thank you for the suggestion.

**Comment by arminms** [comment]
That's really bad practice to introduce new features/bugs to the main branch rather than using a development branch and then merging.

**Comment by hossainemruz** [comment]
The main branch is completely runnable. Just the instructions and configurations has changed which is not documented yet. Isn't it a best practice for user to use a release instead of main branch?

**Comment by arminms** [comment]
That's when there's no `git submodule add https://github.com/hugo-toha/toha.git themes/toha` all over the place!

**Comment by hossainemruz** [comment]
@arminms My apologies, if my previous comment disappointed you. I have updated the **Requirements** and **Usage** section in README.md with new instruction. Please, take a look and let me know if it does work for you.

**Comment by arminms** [comment]
When I try `hugo mod tidy` I get: `Error: module "github.com/hugo-toha/toha/v4" not found`.

**Comment by hossainemruz** [comment]
Can you please share your repository. I am suspecting some configuration issues.

**Comment by arminms** [comment]
Turned out my golang and Node versions were not the minimum mentioned. Updating them solved the problem. Thanks!

**Comment by hossainemruz** [comment]
Hi @salastro, I have updated the quickstart guide. You should be able to run the website from `main` branch.
Ref: https://toha-guides.netlify.app/posts/quickstart/#

**Comment by arminms** [comment]
When I follow *start from scratch* (i.e. not by forking [hugo-toha.github.io](https://github.com/hugo-toha/hugo-toha.github.io)) under Usage, everything works fine but ends up showing serif typeface (e.g. Times New Roman) rather than san-serif typeface (e.g. Arial). Do you know what could be the problem?

**Comment by hossainemruz** [comment]
Look like you forgot to mount the font's from node module. Check the sample here: https://github.com/hugo-toha/hugo-toha.github.io/blob/dd88f0fb7af186f83ece20c507deac61ac324c5c/config.yaml#LL10
