### ISSUE TITLE
add rel="me" on about/socialLinks

### ISSUE THREAD

**Issue by jonathanlang** [hugo-toha/toha#734]
### Describe the solution you'd like

Mastodon allows verifying of links on your profile, but only if you link back to your Mastodon with a rel="me" in the link attributes. 
Currently, the links contain a rel="noopener" parameter, but if this was changed to rel="noopener me" there would be automatic link verification on sites that support this. 

Literally a nice-to-have feature, but should be a simple change. 
Thank you!

### Additional context

For more information, you could read this blog post by [Eric Meyer](https://meyerweb.com/eric/thoughts/2022/11/30/how-to-verify-site-ownership-on-mastodon-profiles/)

**Comment by hossainemruz** [comment]
Sure. We will love to add this feature. I will take a look. No ETA though.

**Comment by hossainemruz** [comment]
Hi @jonathanlang. Added support for rel attribute in social link. Update to latest commit and try adding the link. Check the sample in this link: https://github.com/hugo-toha/hugo-toha.github.io/blob/dd88f0fb7af186f83ece20c507deac61ac324c5c/data/en/sections/about.yaml#L54

**Comment by jonathanlang** [comment]
Thanks for the quick turnaround!
