### ISSUE TITLE
How to run it on Cloudflare Pages?

### ISSUE THREAD

**Issue by arihid** [hugo-toha/toha#742]
### Question
How do I deploy this in Cloudflare Pages?

**Comment by hossainemruz** [comment]
Don't have any official guideline yet. You may check this comment: https://github.com/hugo-toha/hugo-toha.github.io/issues/1#issuecomment-1020754325

**Comment by arihid** [comment]
I have built a working local site, using data from the example site repo.
When I deploy the site to Cloudflare Pages, I got this error:

> Error: Error building site: "/opt/buildhome/repo/content/posts/category/sub-category/rich-content/index.md:24:5": failed to extract shortcode: template for shortcode "img" not found
