### ISSUE TITLE
Slow loading due to Dark Reader

### ISSUE THREAD

**Issue by ornob011** [hugo-toha/toha#745]
The dark theme is causing significant lag in website loading, perhaps because the dark theme has been implemented with the Dark Reader extension. Can I disable the default theming option, but achieve the same dark theme with pure CSS? If yes, how?

**Comment by hossainemruz** [comment]
Yes, currently dark theme is generated by Dark Reader js. This is causing the loading issue. We have to implement the dark theme in CSS. A contribution from the community will be welcome here.
