### ISSUE TITLE
Long time no see, I wonder what happened? Why rewrite the project?

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#751]
### Question

Hi @hossainemruz 
Long time no see, I wonder what happened? Why rewrite the project?

**Comment by hossainemruz** [comment]
Hi @Chow-Ray, the existing site was getting heavy and harder to maintain as code was more or less unstructured. This was the reason for  the re-write.

**Comment by hossainemruz** [comment]
Refactoring has greatly improved the performance. Also, current dark mode implementation is terrible. Want to fix that.

**Comment by hossainemruz** [comment]
Unfortunately, this (#748) happened during the rewrite. Things are good now. Hoping to finish rewriting soon.

**Comment by hossainemruz** [comment]
I am active again. 😃
