### ISSUE TITLE
Changing default color scheme in config.yaml has no effect

### ISSUE THREAD

**Issue by mmzeynalli** [hugo-toha/toha#754]
## Expected Behavior

The default color scheme in config.yaml file is 'system', and it works okay. If you change it to dark, the default color scheme should be dark.

## Current Behavior

However, it does not depend to what you change, it stays in 'system' configuration when you load a page.

## Steps to Reproduce

1. Both in Windows and Debian, changing config.yaml, does not affect end result.
2. Node version: 18.16.0
3. Npm version: 9.6.5
4.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Fixed in #755
