### ISSUE TITLE
Can I set the background image to not downpixelate/blur?

### ISSUE THREAD

**Issue by hwarden162** [hugo-toha/toha#756]
### Question

When I add a background image in the config.yaml it seems that it is either blurred or downpixelated. Is there a way in the config.yaml or somewhere else to set it to use the fully pixelated/non-blurred image? I didn't see any mention of this in the documentation.

**Comment by mmzeynalli** [comment]
By default, it resizes every image there is (post images, bg, profile photo etc.). You can try to match that size by yourself, editing it before applying to website, or try svg format, as it cannot be resized.

**Comment by hossainemruz** [comment]
Added a guide demonstrating how to override default CSS here:
https://toha-guides.netlify.app/posts/customizing/customize-css/
