### ISSUE TITLE
Add social media app handles to sharing message

### ISSUE THREAD

**Issue by f-yanez** [hugo-toha/toha#759]
### Describe the solution you'd like

When people share a post, the message should point to the handle instead of the blog's name. For instance, when sharing a post on the demo website here is the message:

"Rich Content https://hugo-toha.github.io/posts/category/sub-category/rich-content/ via @John's Blog "

Instead, it could read:

"Rich Content https://hugo-toha.github.io/posts/category/sub-category/rich-content/ via @hugo_toha".

### Describe alternatives you've considered

The author file could contain the information for each of the apps handles. If some are not defined, then the default would be the blog's name.

**Comment by hossainemruz** [comment]
Hi @f-yanez, this is controlled by [Open Graph](https://ogp.me). If we want to control the user name for each social media, we have to customize the open graph settings for each social media. That would be tedious thing to maintain.

We add Open graph settings here:
https://github.com/hugo-toha/hugo-toha.github.io/blob/26373cc2acfe4c95e9fc4cf6560fb987be2d6c33/data/en/site.yaml#L24
