### ISSUE TITLE
Small issue about the word gap

### ISSUE THREAD

**Issue by Kellermaan** [hugo-toha/toha#765]
Hi I got a small question about the theme.

![LVOwlXFXhO](https://github.com/hugo-toha/toha/assets/11674190/f711e9e2-658b-48a7-9f90-c3e838143be4)

Just like the picture, sometims it's really unpleasant. do we have any setup can avoid these?

**Comment by hossainemruz** [comment]
Currently, we don't have any easier way to avoid that. You have to use custom CSS to overwrite this.

**Comment by Kellermaan** [comment]
got it, thanks!

**Comment by hossainemruz** [comment]
Added guide on how to customize CSS.
https://toha-guides.netlify.app/posts/customizing/customize-css/
