### ISSUE TITLE
Taken Courses (Show More and Show Less) buttons showed together.

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#771]
## Expected Behavior
Inside taken courses, there should be only one button(Show More) when collapsed, and one button(Show Less) when expanded.

## Current Behavior
Inside taken courses, both buttons are shown when expanded and collapsed. (See screenshots below)

## Possible Solution
Before the major overwrite, these buttons worked perfectly. I will check these changes in the files `assets/scripts/sections/education.js` and `layouts/partials/sections/education.html`. I'll try to fix it.

## Steps to Reproduce
Visit https://hugo-toha.github.io/ to the education section. Also happens on my website.

### Screenshots
![closed](https://github.com/hugo-toha/toha/assets/70479573/f2c66fba-74f7-4077-aa2a-c52837083f9d)

![opened](https://github.com/hugo-toha/toha/assets/70479573/21f19181-cb75-4787-90c8-9f7a95cb3ef3)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
I haven't checked Safari and Explorer, but probably are also affected.

## Detailed Description
I'll try to fix this issue by checking the files `education.html` and `education.js`, as I said before.

**Comment by hossainemruz** [comment]
I can confirm the issue. A PR will be greatly appreciated.
