### ISSUE TITLE
Math rendering with Katex not rendering

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#774]
## Expected Behavior
Katex should render math formulas.

## Current Behavior
The website does not render the formulas using Katex, shows plain text.

## Possible Solution
I don't know yet, I'll check this issue. If I can fix it, I'll do a Pull Request.

## Steps to Reproduce
Just go to https://hugo-toha.github.io/posts/markdown-sample/ and scroll down to `Math Rendering`. This issue also occurs to my website.

### Screenshots
![latex](https://github.com/hugo-toha/toha/assets/70479573/ee592542-a884-4389-9315-d913df5cadf8)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

Haven't checked Edge, Safari, Explorer, probably happens the same.

**Comment by richbai90** [comment]
Did you set math:true in your frontmatter?

```markdown
---
title: "my post"
date: 2023-07-25T16:11:23-06:00
draft: false
math: true
menu:
  sidebar: ...
---

**Comment by BernatBC** [comment]
Of course I did. Is  not a matter of configuration as I had this kattex thing working before the major rewrite. The example website also has the same issue. Also, I have done a Pull Request Fixing this issue.

Thank you for trying to help :)

**Comment by BernatBC** [comment]
As you can see in #775, I was wrong. This works perfectly.
