### ISSUE TITLE
Adding transparent background to certificate badge

### ISSUE THREAD

**Issue by jazzie-bee** [hugo-toha/toha#777]
### Describe the solution you'd like
I didn't see it in the roadmap nor any other issues regarding it. I apologize if I had missed anything.
I noticed the badge for the Certified Kubernetes Security Specialist certificate on the "about me" section had a white background on dark mode.

### Describe alternatives you've considered
I took the liberty of removing the white background and making it transparent. In dark mode it should not show up with a white box border once the new source is linked into the HTML.

### Additional context
Current graphic:
![image](https://github.com/hugo-toha/toha/assets/98238715/30efbc97-997b-4a87-8803-eb9babbae1f3)
 
New suggested graphic(s):

Ver 1 edit
![hugo_toha_io_test_site_screenshot-edit1](https://github.com/hugo-toha/toha/assets/98238715/9ff9a133-c475-4934-b187-cdaabc4d99fa)
Ver 2 edit
![hugo_toha_io_test_site_screenshot-edit2](https://github.com/hugo-toha/toha/assets/98238715/138037e0-5c9f-4c68-a229-823e368cbc09)

I understand the theme is being re-written at the moment. If this issue is being addressed, I apologize.

**Comment by hossainemruz** [comment]
Hi, it would be great if you can send a PR with the updated image. I am more aligned with the second edit.

**Comment by jazzie-bee** [comment]
Do I have to download hugo to edit it as well? Or I can just fork the main repo?

**Comment by hossainemruz** [comment]
Just fork the repo.

**Comment by NSerbin** [comment]
any news about it ?

**Comment by hossainemruz** [comment]
> any news about it ?

Unfortunately, @jazzie-bee didn't get time to send the PR.

**Comment by jazzie-bee** [comment]
Yes, apologies. I haven't had time to work on it. The screenshots from before were just graphic mock-ups I created.
I initially cloned the example site repo, but I can't seem to locate the files for that image. I don't know if I'm missing something in the repo.

If it would be easier, I can share the transparent file itself and someone else edit it.
