### ISSUE TITLE
Feature Request: Modify How Projects/Posts Currently Work

### ISSUE THREAD

**Issue by claytonjack** [hugo-toha/toha#791]
What I am trying to accomplish in short is the ability to host dedicated pages for projects on the site rather than external links. I have tried a few workarounds but currently, I can't get it to work exactly how I would like.

**Required Features:**

- Dedicated page for each project
- Section on the homepage for a list of projects (like we already have)
- Clicking a project on the homepage brings you to that page
- Button on the nav bar that scrolls the page to that section (like we have for all sections)

**I have tried the following but it's not exactly how I would like it:**

1. Use projects as is:

Only able to use external links for projects.

2. Use the posts feature for my projects:

Must enable the "recent posts" section on the homepage. I can easily rename this in the YAML file to "Projects" which changes the header and nav bar text to how I would want it, which is great. I must then enable the posts feature in the main config.yaml. What I don't like about this is that it adds another button to the nav bar and I don't see any way to rename it.

**Solution suggestion:**

The easiest way I can see to implement this with the way the template is currently set up would be to allow users to hide the posts button from the nav bar even if they choose to enable this feature, just like we can with the homepage sections. This way I can write individual posts and then use that link as the URL in the current projects section, although it would be preferred if there was a way to have these links load within the same tab rather than opening a new one.

**Comment by hossainemruz** [comment]
You can hide the section from Navbar by setting `showOnNavbar` to `false`. Here is an example: https://github.com/hugo-toha/hugo-toha.github.io/blob/063dbaebafce133ec200c745e4e1459ed9d972ee/data/en/sections/recent-posts.yaml#L7

I have added guide on how to add custom section. You can add custom section for your projects.
https://toha-guides.netlify.app/posts/customizing/new-section/
