### ISSUE TITLE
On the scroll navbar having the transparent background!!!

### ISSUE THREAD

**Issue by piyush-mahajan** [hugo-toha/toha#806]
### Describe the solution you'd like
On the scroll navbar's text is merging into the content of the site and i would like fix these feature as making the background for the navbar for scroll can you assign me this task?

**Comment by hossainemruz** [comment]
Can you please describe the issue with some screenshot? Please,use the latest commit from main branch.

**Comment by hossainemruz** [comment]
Try updating the theme to latest version. Feel free to re-open if the issue still persist.
