### ISSUE TITLE
Images in cards are distorted

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#808]
## Expected Behavior
Images in post cards should have the original aspect ratio.

## Current Behavior
The images in post cards are distorted, the aspect ratio is not the right one.

## Possible Solution
Modifying css to fix the aspect ratio.

## Steps to Reproduce

1. Go to https://toha-guides.netlify.app/ or https://hugo-toha.github.io/
2. Scroll down to `Recent Posts` section.

### Screenshots
![image](https://github.com/hugo-toha/toha/assets/70479573/c52e6126-48a9-4ff8-bcd3-ac28ff198f43)

### Browsers Affected

- [x] Chrome
- [x] Firefox
Haven't checked the others, but probably is not a browser issue.

**Comment by hossainemruz** [comment]
I can confirm the issue.

**Comment by hossainemruz** [comment]
Btw, @BernatBC how do you feel about the new dark mode?

**Comment by BernatBC** [comment]
Pretty good, but personally I would darken a little bit the light sections.

**Comment by hossainemruz** [comment]
Now, it should be easy to customize the colors. Just change the variables.

**Comment by hossainemruz** [comment]
Please go with first option.

**Comment by hossainemruz** [comment]
Fixed in #819
