### ISSUE TITLE
Netlify deploy failed because of parsing error in the following file

### ISSUE THREAD

**Issue by Nirzak** [hugo-toha/toha#809]
## Expected Behavior
Should be deployed without any errors

## Current Behavior
Got the following error on netlify log during building

```
6:19:13 PM: Error: add site dependencies: load resources: loading templates: "/opt/build/cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20231006193257-e8f8f3b22b76/layouts/partials/helpers/get-section-url.html:1:1": parse failed: template: partials/helpers/get-section-url.html:1: function "page" not defined
```

### Full Error Flow
6:19:13 PM: Error: add site dependencies: load resources: loading templates: "/opt/build/cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugo-toha/toha/v4@v4.0.0-20231006193257-e8f8f3b22b76/layouts/partials/helpers/get-section-url.html:1:1": parse failed: template: partials/helpers/get-section-url.html:1: function "page" not defined
6:19:13 PM: Total in 20 ms
6:19:13 PM: ​
6:19:13 PM: "build.command" failed                                        
6:19:13 PM: ────────────────────────────────────────────────────────────────
6:19:13 PM: ​
6:19:13 PM:   Error message
6:19:13 PM:   Command failed with exit code 255: hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL (https://ntl.fyi/exit-code-255)
6:19:13 PM: ​
6:19:13 PM:   Error location
6:19:13 PM:   In build.command from netlify.toml:
6:19:13 PM:   hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
6:19:13 PM: ​
6:19:13 PM:   Resolved config
6:19:13 PM:   build:

**Comment by Nirzak** [comment]
The main issue is on the following line of this link "https://github.com/hugo-toha/toha/blob/main/layouts/partials/helpers/get-section-url.html"

```
{{- if page.IsHome -}}
```
It was trying to say that page function is not defined!

**Comment by Nirzak** [comment]
it's may be related https://github.com/gohugoio/hugo/issues/10774

**Comment by Nirzak** [comment]
Ok this is working when using hugo version 0.119 ! I don't know still how have you deployed this with hugo version 0.109

**Comment by hossainemruz** [comment]
Thank you for reporting. We should update the minimum Hugo version required for the theme.

**Comment by Nirzak** [comment]
> Thank you for reporting. We should update the minimum Hugo version required for the theme.

Yeah. I think it has been fixed on hugo version 0.111.1 though I haven’t tested as I am using the latest hugo version but assuming it from the issue’s milestone on hugo’s github repo.

**Comment by hossainemruz** [comment]
I have updated Hugo version in netlify.toml of the example repos.

**Comment by Nirzak** [comment]
> I have updated Hugo version in netlify.toml of the example repos.

Thanks Emruz bhai!
