### ISSUE TITLE
Add Open Graph tags to header

### ISSUE THREAD

**Issue by drem-darios** [hugo-toha/toha#81]
The Open Graph Protocol enables rich content when sharing a website (https://ogp.me/).  I recommend adding the ability to customize the open graph tags in the header.

**Comment by drem-darios** [comment]
Here is what I suggest can be added to the header.html file. This allows users to customize the most important tags.
`
<meta property="og:site_name" content="{{ .Site.Params.openGraph.siteName | default .Site.Title}}"/>
<meta property="og:title" content="{{ .Site.Params.openGraph.title | default .Site.Title}}"/>
<meta property="og:description" content="{{ .Site.Params.openGraph.description | default .Site.Params.description }}"/>
<meta property="og:image" content="{{ .Site.Params.openGraph.image | default .Site.Params.logo.main }}">
<meta property="og:url" content="{{ .Site.Params.openGraph.url | default .Site.BaseURL }}">
<meta property="og:type" content="{{ .Site.Params.openGraph.title | default "website"}}"/>
`

**Comment by alex-bezek** [comment]
@drem-darios hugo offers the ability to customize opengraph settings via an internal template https://gohugo.io/templates/internal/#open-graph
Does that enable what you are looking for or are there more customizations needed?

**Comment by alex-bezek** [comment]
So this is what it would do to the posts pages
![image](https://user-images.githubusercontent.com/8029578/97092457-0ee45700-1612-11eb-9bac-22ca16fba899.png)

However, one problem with the open-graph internal template is that it won't take into account internationalization for the main home page for the description like we do here https://github.com/hossainemruz/toha/blob/master/layouts/index.html#L12

![image](https://user-images.githubusercontent.com/8029578/97092479-363b2400-1612-11eb-8534-4798095bdd20.png)
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html#L2
You could technically add the description config back into the main config.yml if you wanted.

If internationalization isn't a strong requirement, it would technically be simplest to use the internal template to align with hugo standards and not create more custom config options, but it won't be as flexible as something like what @drem-darios posted above

**Comment by tanho63** [comment]
Echoing this request (also for Twitter cards)!

**Comment by hossainemruz** [comment]
Added OpenGraph header in #333. Used Hugo internal template for the post pages. Added a custom template for home page to handle the internationalization.

Check this PR to see how to customize the headers.
https://github.com/hugo-toha/hugo-toha.github.io/pull/77
