### ISSUE TITLE
Search Bar text is black when using dark mode

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#810]
## Expected Behavior
The text of the search bar should be white when using the website in dark mode.

## Current Behavior
The text of the search bar is black when using the website in dark mode.

## Possible Solution
Changing the css should fix this issue.

## Steps to Reproduce

1. Visit https://hugo-toha.github.io/posts/ and try searching for posts.

### Screenshots
![image](https://github.com/hugo-toha/toha/assets/70479573/b9db2138-5caf-489a-bc4e-8393707abf44)
![image](https://github.com/hugo-toha/toha/assets/70479573/d23b0818-832c-4643-8e09-1a0a51ac353d)

### Browsers Affected

- [x] Chrome
- [x] Firefox

## Detailed Description
I'll try to fix it in the css.

**Comment by hossainemruz** [comment]
I can confirm the bug. Should be easy to fix. A PR will be much appreciated.
