### ISSUE TITLE
Result cards after searching have wrong format.

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#811]
## Expected Behavior
After searching for posts, cards should look like the second screenshot below.

## Current Behavior
After searching for posts, cards look like the first screenshot.

## Possible Solution
When getting the result from the search query, a card is made 'manualy' instead of using the `partials/cards/post/`. Making the transition from this card made only for the search results to  `partials/cards/post/` should fix it.

Moreover, by using the partial code `partials/cards/post/` should fix the issue of elements missing like tags and time to read.

## Steps to Reproduce

1. Visit https://hugo-toha.github.io/posts/ and make a search query.

### Screenshots
![image](https://github.com/hugo-toha/toha/assets/70479573/a74fc2e3-2f0c-4ca4-8f3b-166707ae8e40)
![image](https://github.com/hugo-toha/toha/assets/70479573/274f2868-9eec-45c3-934c-8b26f2475d9e)

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by hossainemruz** [comment]
I can confirm the issue.
