### ISSUE TITLE
Adding a Back to top button

### ISSUE THREAD

**Issue by BALASARVAN12** [hugo-toha/toha#823]
### Describe the solution you'd like
 To enhance the user experience while browsing through a vast portfolio, adding a "back-to-top" button can significantly improve accessibility and ease of scrolling for the users.

Adding a "back-to-top" button can significantly improve user experience by allowing users to quickly return to the top of the page without manually scrolling. 

### Additional context

Please assign this issue to me under HactoberFest2023.

**Comment by hossainemruz** [comment]
We already have a scroll to top button.
![Screenshot from 2023-10-28 11-09-45](https://github.com/hugo-toha/toha/assets/12577390/0fbe1446-768c-42e6-8d7d-64f3f955a1d5)

**Comment by BALASARVAN12** [comment]
oh okay @hossainemruz

**Comment by BALASARVAN12** [comment]
![image](https://github.com/hugo-toha/toha/assets/91976828/f8b39632-fc7a-470f-b682-f8f12ef1fd9d)

but on main page of website there is now back to top button

**Comment by hossainemruz** [comment]
This is intentional. In the main page, you have the top navbar to navigate between any section including the top section. So,adding scroll-to-top there will be redundant.

**Comment by BALASARVAN12** [comment]
okay @hossainemruz 

I have a new idea for the footer **The Slideout Footer**, so can I create a new issue

**Comment by hossainemruz** [comment]
Sure. Create a new issue and close this one.

**Comment by BALASARVAN12** [comment]
okay @hossainemruz
