### ISSUE TITLE
Add company logo in the experience section

### ISSUE THREAD

**Issue by niltied** [hugo-toha/toha#827]
### Describe the solution you'd like

Hello, I would like to have the possibility to : 

1. Add the company logos (small PNG or jpg format) next to their name in the experience section. 
2. Have the same functionality for the Education section (maybe on the left near school name).

### Additional context

Is it possible to assign this issue under HacktoberFest 2023 please ? Thank !

**Comment by hossainemruz** [comment]
Sure. Assigned under HacktoberFest 2023

**Comment by niltied** [comment]
Thank a lot @hossainemruz
