### ISSUE TITLE
How to add a page

### ISSUE THREAD

**Issue by darbymartinez** [hugo-toha/toha#83]
Hello, I want to add a page to toha. I tried to do it by creating a markdown file which I placed in the data folder but I kept getting this error. 

 unmarshal of format "" is not supported

Is there a specific folder where I can put a markdown file to create a new page? Does toha support a different syntax?

**Comment by hossainemruz** [comment]
What do you mean by page? Did you mean post?

**Comment by dabymartinez** [comment]
No, I mean like creating a page that is not the homepage and its sections.

**Comment by hossainemruz** [comment]
Well, then it's not that easy. You have to create a custom layout for your page. Eventually, I will write a post about how to add custom layout but I can't do it  now.

This branch has an example of custom layout.
https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/

Check the `layout` folder. It creates two layout. One for about page and another for contact me page. Once you have created the layouts, you have to write your markdown text in `content/<layout name>/_index.md`. Check the `content/about` and `content/contact` folder for sample.

**Comment by serverfriendsorg** [comment]
I have the same issue, I want to add a page for the imprint but can't figure out how.
@hossainemruz in which branch can I find a custom layout as described in the last comment?

**Comment by hossainemruz** [comment]
Didn't notice that I have provided wrong link for custom layout. Btw, here is the branch with custom layout: https://github.com/hossainemruz/toha-example-site/tree/custom-layout

**Comment by alex-bezek** [comment]
@hossainemruz since I'm documenting how to add a custom section now as part of https://github.com/hossainemruz/toha/issues/87 I can probably tackle this as well. I am a little confused though, is the request to add a custom section on the main page (like issue 87) or to add a completely standalone page with its own route and everything? Would it need to show up in the navigation?

**Comment by hossainemruz** [comment]
@alex-bezek I think we should document both adding a new section and a new page. User can use `customMenus` option if they want to show it in navigation.

**Comment by alex-bezek** [comment]
PR opened here https://github.com/hugo-toha/guides/pull/13

**Comment by JPUnD** [comment]
I have a bit of experience with Hugo and I've managed to pick another theme (Elate) and split it's sections into separate pages. Yet in this case I fail to see how should I do so.

**Comment by hossainemruz** [comment]
Here is a guide on how to add new section:
https://toha-guides.netlify.app/posts/customizing/new-section/
