### ISSUE TITLE
Unable to run local webserver when offline, Failed to get JSON resource from twitter?!

### ISSUE THREAD

**Issue by MrPenguin07** [hugo-toha/toha#831]
## Expected Behavior

Server should build regardless whether it can phone home to twitter or not.

## Current Behavior

$ hugo server -w
Watching for changes in /home/xxxxxxx/{archetypes,assets,content,data,node_modules,package.hugo.json,package.json,static}
Watching for config changes in /home/xxxxxxxxx/config.yaml, /home/xxxxxxxxx/go.mod
Start building sites …
hugo v0.118.2+extended linux/amd64 BuildDate=unknown VendorInfo=gentoo:0.118.2

ERROR Failed to get JSON resource "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2FSanDiegoZoo%2Fstatus%2F1453110110599868418": Get "https://publish.twitter.com/oembed?dnt=false&url=https%3A%2F%2Ftwitter.com%2FSanDiegoZoo%2Fstatus%2F1453110110599868418": dial tcp: lookup publish.twitter.com on 192.168.2.9:53: server misbehaving
Built in 597 ms
Error: error building site: logged 1 error(s)

## Possible Solution

Remove requirement to fetch anything from twitter

## Steps to Reproduce

- Follow documentation to build locally

Somewhat similar to #122 

I suppose this is due to the recent twitter/X restrictions on API and forced logins.
FWIW i've already disabled any reference to twitter;

$ cat config.yaml | grep twitter
   twitter: false

**Comment by MrPenguin07** [comment]
Update;
It seems this twitter domain is being blocked by my upstream dns blocklist.

However I think it wise to remove the dependency on calling home to twitter servers to run the hugo server locally, especially when twitter is set to false.

This would also occur if one was simply offline.

**Comment by hossainemruz** [comment]
There are quite a few sample showcased that requires internet connection. So, making it working offline would require to disable them all.

**Comment by MrPenguin07** [comment]
> There are quite a few sample showcased that requires internet connection. So, making it working offline would require to disable them all.

I was thinking more error handling, that if the request 404's then the local server can run regardless.

**Comment by hossainemruz** [comment]
I don't think we have any way to do that.
