### ISSUE TITLE
Two companies/designations in the `about.yaml` section?

### ISSUE THREAD

**Issue by dietervansteenwegen** [hugo-toha/toha#848]
I have a regular day job but also have my own small company on the side. Is there a way to display both in the  `about` section?

I've tried just adding a second `designation` and `company` section, but then only the second is parsed/kept.

In case this is not possible I'll just remove the section and put both in the `experiences` section.

I'm not yet fluent enough with Hugo to figure out where to look for the answer in the source code myself...

**Comment by hossainemruz** [comment]
Hi @dietervansteenwegen! If you keep designation part empty, then the that section won't show up.

**Comment by dietervansteenwegen** [comment]
Thanks! So if I understand correctly, there is no way to have two companies/jobs mentioned in that section?

**Comment by hossainemruz** [comment]
Unfortunately no.

**Comment by dietervansteenwegen** [comment]
Ok, thanks. Still very happy with Toha theme! Thank you for your work....
