### ISSUE TITLE
Support for categories or tags (filtering, display)

### ISSUE THREAD

**Issue by dietervansteenwegen** [hugo-toha/toha#859]
I've been working on a site for a while now, mostly migrating away from WordPress.

I've forked Toha to implement something I needed (see #848). Now I'm looking for a way to display tags and/or categories for each post, which are included in the frontmatter. 

Starting from a MarkDown file like this:

``` markdown
  ---
title: "Novastar MCTRL300 basic control software"
date: "2023-02-13"
categories: 
  - "development"
  - "software"
tags: 
  - "Novastar"
  - "python"
---

```

I'd like to have tags displayed in the in the post overview as well as in the post. Additionally, I'd like to be able to filter on either tags or categories.

The theme supports putting posts in a project categories, but that only offers one "tag".

I think (if not using a theme), this can be accomplished using taxonomies, but need to look further into that.

So, I'd like to know if there's an obvious way to do this using the Toha theme? Maybe I'm overlooking something? Maybe I just need to get to know Hugo better?

Any pointers would be appreciated!

**Comment by hossainemruz** [comment]
>I'd like to have tags displayed in the in the post overview as well as in the post

We already do that. Just look at the first and third post card:
https://hugo-toha.github.io/posts/

>Additionally, I'd like to be able to filter on either tags or categories.

Already supported. The tag button is a link. Just click on the tag to filter all posts with this tag.

**Comment by dietervansteenwegen** [comment]
@hossainemruz That's just great!

All the posts I have include the categories and tags as in your examples but the tag buttons don't show up. There must be some kind of configuration or setup I haven't done yet/correctly.

I'll go over the page you mentioned again and see if I can figure out where I need to make changes.

In any case, thank you for sharing your work. It's a good looking theme!

**Comment by hossainemruz** [comment]
Yes. You have to enable it in `config.yaml`. First, make sure you are using latest version of theme.
- https://github.com/hugo-toha/hugo-toha.github.io/blob/063dbaebafce133ec200c745e4e1459ed9d972ee/config.yaml#L178

**Comment by dietervansteenwegen** [comment]
Seems like I just needed to add

```yaml
module
  params
    tags:
      enable: true
      on_card: true # enables tags in post cards
```

to get the tags working. I'll need to look into the categories a bit more, but so great that it is already included!

**Comment by dietervansteenwegen** [comment]
I started from the example site and learned from the setup, but seems like I removed the `tags` config somewhere in the process. I'll go over everything again. I've got a couple of other "strange" things I need to look at but I'm quite certain those are mistakes on my end, not an issue with the theme :).

**Comment by hossainemruz** [comment]
Thank you. Please, consider closing this issue.

**Comment by dietervansteenwegen** [comment]
Will do, and thank _you_ for all your work on this!
