### ISSUE TITLE
No sidebar, No ToC in my Blog

### ISSUE THREAD

**Issue by niltied** [hugo-toha/toha#862]
## Expected Behavior

Hi @hossainemruz,

I've just install from scratch full hugo instance with toha v4.1.1. Everything work fine.
I have enabled Blog Posts features and TOC features in reading page in my `params.features` section of my ```hugo.yaml``` file.

```markdown
# Site parameters
params:
  # Background image of the landing page
  background: images/site/windows.jpg

  # GitHub repo URL of your site
  # gitRepo: https://github.com/hugo-toha/hugo-toha.github.io

  features:
    # Enable dark theme
    darkMode:
      enable: true

    # Enable portfolio section
    portfolio:
      enable: true

    # Enable blog posts
    blog:
      enable: true

    # Enable Table of contents in reading page
    toc:
      enable: true
```
I write my first post with a lot of titles for my TOC as describe [here](https://toha-guides.netlify.app/posts/writing-posts/organizing/category/). 

```markdown
---
title: "Analytics and Comments"
date: 2024-01-13T17:00:23+01:00
hero: /images/posts/writing-posts/analytics.svg
description: Adding analytics and disquss comment in hugo 
theme: Toha
menu:
  sidebar:
    name: Analytics & Comments
    identifier: analytics-and-comments
    weight: 500
---

# Titre 1
## Titre 1.1
## Titre 1.2
# Titre 2
## Titre 2.1
## Titre 2.2
## Titre 2.3
# Titre 3
## Titre 3.1
### Titre 3.1.1
### Titre 3.1.2
## Titre 3.2
```

I see it in my Blog, **but I don't see my sidebar menu on the left, and I don't see my ToC too**. 

I don't understand. Any idea ?

Thanks

Hugo Version : 0.121.4
Toha Version : 4.1.1

### Browsers Affected

- [ ] Chrome (not tested)
- [X] Firefox
- [X] Edge
- [ ] Safari 11 (not tested)
- [ ] Safari 10 (not tested)
- [ ] IE 11 (not tested)

**Comment by hossainemruz** [comment]
Can you please share the URL for your blog?

**Comment by niltied** [comment]
Check here : https://hugo.dietlin.eu

**Comment by hossainemruz** [comment]
I can see the sidebar and TOC. 
![image](https://github.com/hugo-toha/toha/assets/12577390/788b0f7e-e1b7-4534-a35e-2adf4c4b9766)

**Comment by niltied** [comment]
Hum... It's OK for me too. In fact, it was my zoom in my Firefox fixed to 110%. You can close my issue.
Thank a lot Emruz for your test and feedback. See you next time !
