### ISSUE TITLE
Hide author name and image in post?

### ISSUE THREAD

**Issue by dietervansteenwegen** [hugo-toha/toha#867]
### Question

I'd like to hide the author image and name for all posts. Since it is my site/blog, it is kind of obvious that the posts were by me.
Is there a way (frontmatter? `_index.md`? ...?) to hide it?

I've seen other themes that support the `profile: false` in the front matter, but that does not seem to work for this theme. 
I'm sure I can change it in my own fork of the theme, but maybe there is a simple, standard way to do it.

Thanks!

**Comment by dietervansteenwegen** [comment]
Obviously, I understand the usefulness of having the option to support multiple authors. It is just that I would prefer not to use it ;).

**Comment by BernatBC** [comment]
As far as I know, there's no option to do it. If I have time I might do it in the following days.

You could try removing the author lines inside `/layours/_default/single.html`
If you're stuck, you can follow [this](https://toha-guides.netlify.app/posts/customizing/customize-layout/) guide.

**Comment by dietervansteenwegen** [comment]
@BernatBC Thanks!

I'm pretty confident I can get it to work by disabling it altogether in my own fork of the theme, but figured there might be a simple config setting that I didn't know about. Seems there isn't, and I'll look at modifying the theme.

Thanks again.

**Comment by hossainemruz** [comment]
I think it is a reasonable feature request. We can introduce a configuration option to disable the author section in post.

**Comment by dietervansteenwegen** [comment]
I'd propose to try and do it myself but I don't expect that will work out well. I can try though. I'd first need to find out how to access the front matter and then change the templating.

**Comment by dietervansteenwegen** [comment]
@BernatBC Thank you very much. Looking at the commits in the pull request, it would have taken me an awful long time to come up with something that was portable and not just a hack for my own use.
