### ISSUE TITLE
Bug: extra anchor in post card tags

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#868]
## Expected Behavior
Tags in post cards shouldn't have the extra anchor.

## Current Behavior
Tags in post cards have an extra anchor, which will result to having an extra button in the tags.

## Steps to Reproduce

1. Visit https://hugo-toha.github.io/
2. Scroll down to Recent Posts, and you'll see this in the Rich Content post

### Screenshots
![bug](https://github.com/hugo-toha/toha/assets/70479573/a2106e5f-4e5d-490b-8885-05958e3b5618)

## Detailed Description

I've been investigating for a while, and notticed that the whole card anchor adds the anchor to the list, couldn't find an easy way to fix it.

**Comment by hossainemruz** [comment]
I have also noticed the issue. Couldn't find a quick solution so I kept it like this. 😞
