### ISSUE TITLE
Gallery 

### ISSUE THREAD

**Issue by darbymartinez** [hugo-toha/toha#87]
Is there a way to add a picture gallery to this theme?

**Comment by hossainemruz** [comment]
Yes. You have to add a custom section.

**Comment by alex-bezek** [comment]
@hossainemruz I've been going through your backlog because I'm thoroughly enjoying your theme and would like to help out more. Would you like to turn this issue into "Document how to make a custom section" for the toha-example-site repo and have me take a stab at it?

**Comment by hossainemruz** [comment]
Sure @alex-bezek . That would be great.

**Comment by hossainemruz** [comment]
Added guide on how to add new section.
https://toha-guides.netlify.app/posts/customizing/new-section/
