### ISSUE TITLE
New french translation about Note feature on the navbar

### ISSUE THREAD

**Issue by niltied** [hugo-toha/toha#872]
Hi,

Just a little request, easy to revolve.

### Definition of Ready

When Toha was configured in French **AND** Notes feature is enabled in `config.yaml` (or alternatively `hugo.yaml`), Notes title in the navbar, is translated as `Remarques` in French. It's a really strange title in the navigation bar for french people. It's better to keep `Notes` title in French too, just like English. 

### Definition of Done

- [x] Change the french Translation about `Remarques` word for the Notes feature in the navbar.
- [x] It mustn't also forget the same translation on Root menu in the sidebar on the Notes frontend.

Is it possible to change this to the next minor release of Toha @hossainemruz ?

Thank,

**Comment by BernatBC** [comment]
You can modify the file `i18n/fr.toml`, changing the following lines:

```toml
[notes]
other = "Remarques"
```

to:

```toml
[notes]
other = "Notes"
```

**Comment by niltied** [comment]
Hi @BernatBC and @hossainemruz,

So, it's done. See my MR #875. Thank U @BernatBC for your guide. Effectivly, it was easy to solve even for me.
