### ISSUE TITLE
[Bug] Extra whitespace after code block

### ISSUE THREAD

**Issue by FunctionalHacker** [hugo-toha/toha#874]
## Expected Behavior
The code blocks should be shown as befor with Toha v3

## Current Behavior
Recently upgraded my site to Toha v4 and after that, I can see there is a lot of extra white space after code blocks and figure captions.

My site's content is written with AsciiDoc, so it might be the cause here. I tried recreating the issue with Markdown on my site and it worked as predicted.

## Possible Solution
I believe the behaviour is caused by one or both of these lines https://github.com/search?q=repo%3Ahugo-toha%2Ftoha+min-height%3A+130&type=code
Disabling the `min-height` property in the browser seemed to fix the issue but still the padding values are a bit weird. 
![image](https://github.com/hugo-toha/toha/assets/16839187/850deedb-60d2-478b-b2b0-1d3cb8c6ff73)

I would have created a PR but I'm not comfortable making the change since I don't know the inner workings of this theme. Looks like the CSS definitions that cause this might have an effect on other parts of the theme as well, so simply removing them might cause regressions.

The problem with the code blocks can be seen on my website here https://korhonen.cc/posts/migrate_misskey_root_account/#_solution

Figure captions also have a similar problem https://korhonen.cc/posts/creating_this_site/#_future_plans

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge (not tested)
- [ ] Safari 11 (not tested)
- [ ] Safari 10 (not tested)
- [ ] IE 11 (not tested)

**Comment by hossainemruz** [comment]
I am wondering why you are seeing this extra code spaces! The example site has both codeblocks and figures but none has additional spaces after them.
https://hugo-toha.github.io/posts/markdown-sample/

**Comment by FunctionalHacker** [comment]
My site content is written in AsciiDoc and the example site is written in Markdown as far as I know. I think we should look at the different HTML structures created by the respective HTML generation pipelines

**Comment by FunctionalHacker** [comment]
The example page seems to have a structure like this

```html
<pre>
   <code></code>
<pre>
```

While my site, which is generated by AsciiDoctor, has an extra div around a similar structure

```html
<div class="content">
   <pre>
      <code></code>
   <pre>
</div>
```

Don't know enough about the inner workings of Hugo or AsciiDoctor to research this much further. Any ideas?

**Comment by hossainemruz** [comment]
That makes sense. I will check if we can reset the CSS for the `content` class with code.

**Comment by FunctionalHacker** [comment]
I did some more research and found a way to make AsciiDoctor play more nice with Hugo, using a custom html5 backend https://cosmos547.moe/posts/hugo-with-asciidoc/

Sorry for wasting your time. I was sure it was not an issue with my site since I've ran it without issue with v3 such a long time. Hope this issue serves as a help resource if anyone else runs into the same issue.
