### ISSUE TITLE
Hovering a post card tag does not change appearance

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#893]
## Expected Behavior

Hovering a post tag should change it's appearance in the same way as project and publication tags.

## Current Behavior

Hovering a post tag doesn't change anything.

## Possible Solution

Will modify CSS file to fix it.

## Steps to Reproduce

1. Visit https://hugo-toha.github.io/
2. Scroll down to recent posts
3. Hover over the tags of "Rich Content" post.

## Detailed Description

I will fix it this week.

**Comment by BernatBC** [comment]
Also, I would like to ask if this behaivour should work with the tags in post pages.

**Comment by hossainemruz** [comment]
Yes. They should have same hover effect as the buttons.
