### ISSUE TITLE
Change /icons Directory Path

### ISSUE THREAD

**Issue by austinarbor** [hugo-toha/toha#897]
Hello,
Could you change the icons directory from `/icons` to another directory, or make it configurable? I am self hosting on apache2, and apache2 comes with default behavior that rewrites requests to`/icons/..` to something else.

The behavior is defined in `/etc/apache2/mods-available/alias.conf`

I tried disabling the module but the site basically fails to load at all for me without it. Unfortunately I am not experienced enough with apache config to know what I need to do to fix that behavior.

If there is an easy way to configure the directory to be different I would be interested in that solution also

```
<IfModule alias_module>
	# Aliases: Add here as many aliases as you need (with no limit). The format is
	# Alias fakename realname
	#
	# Note that if you include a trailing / on fakename then the server will
	# require it to be present in the URL.  So "/icons" isn't aliased in this
	# example, only "/icons/".  If the fakename is slash-terminated, then the
	# realname must also be slash terminated, and if the fakename omits the
	# trailing slash, the realname must also omit it.
	#
	# We include the /icons/ alias for FancyIndexed directory listings.  If
	# you do not use FancyIndexing, you may comment this out.

	Alias /icons/ "/usr/share/apache2/icons/"

	<Directory "/usr/share/apache2/icons">
		Options FollowSymlinks
		AllowOverride None
		Require all granted
	</Directory>

</IfModule>
```

**Comment by BernatBC** [comment]
Hi @austinarbor,
you could copy the file https://github.com/hugo-toha/toha/blob/main/layouts/partials/navigators/theme-selector.html into `/layouts/partials/navigators/theme-selector.html` of your site, and modify the paths from `icons/` to your desired path.

**Comment by austinarbor** [comment]
@BernatBC thanks for the quick response - that works. I actually ended up getting so annoyed with apache about this I switched to nginx and that's been working out of the box for me also
