### ISSUE TITLE
When I push to my repository deployed on gh-pages, the custom domain field goes blank. This has been happening since I updated from Theme version 3 to version 4.

### ISSUE THREAD

**Issue by javierasping** [hugo-toha/toha#901]
Good morning!!

Not long ago, I asked for help here because I was unable to automatically update the theme, but you helped me solve it.

However, since then I've noticed that whenever I push to the repository, the custom domain field goes blank. It should have the value www.javiercd.es.

After reading some forums, I was told to place a CNAME file with my domain (www.javiercd.es) in the root directory, but it hasn't had any effect; the field keeps getting "erased."

The correct configuration is as follows:

![image](https://github.com/hugo-toha/toha/assets/80594036/d1f5f3ff-3448-425f-8ebf-23e8efae0caa)

But I don't understand why it goes blank when I push.

I'm not sure if you've experienced something similar or know where I might have made a mistake. Thank you very much in advance.

**Comment by BernatBC** [comment]
Try placing the CNAME file inside the `static` directory.

**Comment by javierasping** [comment]
I have tried it but the same thing keeps happening.

![image](https://github.com/hugo-toha/toha/assets/80594036/933566b8-8c8e-4770-96ff-cd41c213f34a)

After making the change, I pushed again to verify it, and once more, it deleted the custom domain field. And it deploys to the domain javierasping.github.io

![image](https://github.com/hugo-toha/toha/assets/80594036/b23ddfec-817d-4997-9134-d5f9f7745cdc)



https://github.com/javierasping/sentinel

**Comment by BernatBC** [comment]
I've checked your repo, and you need to add:
```yaml
  - source: static
    target: static
```
under module imports

**Comment by javierasping** [comment]
Thank you very much!!! That fixed it. By the way, I've seen your website and it looks really cool!
