### ISSUE TITLE
Feature Request: Show different pictures for dark theme

### ISSUE THREAD

**Issue by BernatBC** [hugo-toha/toha#902]
### Describe the solution you'd like
Sometimes you'd like to have different images depending on the use of the light and dark theme. For example, in the education section, we could add:

```yaml
logo-dark: /images/logo-dark.png
```

In the case no `logo-dark` attribute is given, the `logo` attribute will be considered for displaying the picture in the light mode.

Also, I'll code it myself when I find some time.

### Describe alternatives you've considered
I've also considered inverting the colors of the pictures, but only work in certain images. For a more global solution, the capability of having distinct images looks better.

**Comment by hossainemruz** [comment]
Sounds good to me.

**Comment by jamesdeluk** [comment]
Can this also be done for the front page logo? i.e.
```
params:
  logo:
    main: logo.png
    dark: dark-logo.png
```

**Comment by hossainemruz** [comment]
> Can this also be done for the front page logo? i.e.
> 
> ```
> params:
>   logo:
>     main: logo.png
>     dark: dark-logo.png
> ```

Unfortunately, no.

**Comment by jamesdeluk** [comment]
> > Can this also be done for the front page logo? i.e.
> > ```
> > params:
> >   logo:
> >     main: logo.png
> >     dark: dark-logo.png
> > ```
> 
> Unfortunately, no.

As in, it's not technically possible, or it's not a feature that will be implemented?

**Comment by hossainemruz** [comment]
>As in, it's not technically possible, or it's not a feature that will be implemented?

Can be implemented. Please, file a feature request.
