### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by hawkeye116477** [hugo-toha/toha#906]
### Describe the solution you'd like

Migrate to Bootstrap 5.

### Additional context

This theme looks not bad, but could be even better if it will be upgraded to latest Bootstrap 5.

Btw, link to roadmap is broken.

**Comment by BernatBC** [comment]
Hi @hawkeye116477. I just updated bootstrap to my site, and I encountered so many bugs that it will take some time. Right now, I don't have much free time to deal with those bugs.
