### ISSUE TITLE
Cannot see Hero images on my posts after theme update

### ISSUE THREAD

**Issue by MarionMoseby** [hugo-toha/toha#907]
## Expected Behavior
Post images should appear

## Current Behavior
In [my personal website](https://codeberg.org/FlyingFlamingo/pablomarcos-me/), after the last theme update, I cannot see images for the posts, unless they are located in /images.

Maybe there is an error in configuration in my part? I just dont know what to do :+

## Steps to Reproduce
1. `git clone https://codeberg.org/FlyingFlamingo/pablomarcos-me/`
2. `cd pablomarcos-me/`
3. `hugo serve -w`

### Screenshots
![imagen](https://github.com/hugo-toha/toha/assets/48572431/3127c68e-4c48-42a2-8213-84496472d9e0)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description
EDIT: It seems like the issue is related to the language configuration; if I add index.en.md to a post, the image shows up
EDIT 2: The issue seems to have something to do with the default language, because, if I Set `
defaultContentLanguage: de; defaultContentLanguageInSubdir: true`, it works back. Is having a main blog lang separated from the main page lang not supported anymore?

**Comment by hossainemruz** [comment]
We haven't changed anything related Language in recent updates. Probably, the behavior has changed in Hugo itself.

**Comment by MarionMoseby** [comment]
Thank you! So, I am guessing, nothing you can do right?

**Comment by hossainemruz** [comment]
Yes

**Comment by MarionMoseby** [comment]
Closing then :p
