### ISSUE TITLE
Day of week missing in Finnish

### ISSUE THREAD

**Issue by FunctionalHacker** [hugo-toha/toha#926]
## Expected Behavior
The day of week, f.ex "Perjantai" should be visible in Finnish

## Current Behavior
The day of week is rendered as "cccc"

## Possible Solution

This is likely a missing translation somewhere. I tried to go through the source code and documentation of both Hugo and this theme, but couldn't find a place where this could/should be contributed.

#### Finnish (not working)
![image](https://github.com/hugo-toha/toha/assets/16839187/88314613-24d1-48b4-a049-9543f147a42d)
https://korhonen.cc/fi/korhonen_aur/

#### English (working)
![image](https://github.com/hugo-toha/toha/assets/16839187/9f7b9cc5-1dba-47f8-8275-6943cb76eae0)
https://korhonen.cc/korhonen_aur/

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by BernatBC** [comment]
Dates are provided by hugo. You can open an issue in this repo: https://github.com/gohugoio/hugo.

**Comment by FunctionalHacker** [comment]
Thanks a lot. Sorry for the noise
