### ISSUE TITLE
How to disable "light" theme?

### ISSUE THREAD

**Issue by tht** [hugo-toha/toha#931]
It is documented how to enable the dark theme (https://toha-guides.netlify.app/posts/customizing/dark-theme/). But what if I *only* want the dark theme? It does not seem to be possible to disable the light theme.

### Question
Is it even possible to only use the dark theme?

**Comment by hossainemruz** [comment]
No. It is currently not possible.

**Comment by joyao** [comment]
This feature has been implemented. Please pull the latest code.
