### ISSUE TITLE
Dark to Light Mode Switcher

### ISSUE THREAD

**Issue by 33masterman33** [hugo-toha/toha#941]
Hello, I've been building my portfolio and wanted to add the button to switch from dark to light mode. I could not figure out how to enable it in my config files.

Here is a screenshot of the button from the example site. 
<img width="52" alt="image" src="https://github.com/hugo-toha/toha/assets/35201468/fa28b033-2bae-467c-aa8c-3ce57ac90368">

**Comment by hossainemruz** [comment]
You only need to enable dark theme in your `hugo.yaml` file. Here,is an example: https://github.com/hugo-toha/hugo-toha.github.io/blob/b4192719c87f1be72763eff611c0ec28d31032e8/hugo.yaml#L83

**Comment by 33masterman33** [comment]
Thank you! I realized while i had added the darkmode setting it was not under features so it did not get applied. It's working now.
