### ISSUE TITLE
bug , The icon in the top bar is not working

### ISSUE THREAD

**Issue by javierasping** [hugo-toha/toha#944]
I just accepted a PR for a theme update, and the icon for selecting dark or light mode has stopped working. Additionally, on mobile, when the icon with the three parallel lines is tapped, it doesn't do anything

![image](https://github.com/hugo-toha/toha/assets/80594036/75a42764-659f-4bff-8a9f-4fd28101fb6e)

![image](https://github.com/hugo-toha/toha/assets/80594036/a823c6a1-90cb-4e32-bc23-c9c6649e5454)

All the other buttons work normally.

This is my repo --> https://github.com/javierasping/sentinel
My page is [www.javiercd.es ](www.javiercd.es)

**Comment by hossainemruz** [comment]
I am suspecting you did not update the dependencies properly. Please, execute these commands:

```bash
# update to latest version of all modules
hugo mod get -u

# update the npm dependencies
hugo mod npm pack

# cleanup go.sum file
hugo mod tidy

# install npm depnedencies
npm install
```

**Comment by niltied** [comment]
Hi @hossainemruz,

Same issue here. However, I always update the dependencies as you indicate in my pipeline. No errors in my build job. The icon does not appear on my smartphone.

**Comment by javierasping** [comment]
I just updated the modules and dependencies locally, but it still doesn't work. Personally, I have it deployed on GitHub with actions, and it doesn't give any errors.

**Comment by hossainemruz** [comment]
@niltied , @javierasping can you please point me to your repository? I am suspecting you are still using bootstrap 4.x. We have updated to bootstrap 5.x.

**Comment by javierasping** [comment]
Yes, mine is https://github.com/javierasping/sentinel.

**Comment by hossainemruz** [comment]
@javierasping why did you duplicated the layout files? Those files have changed. Since, you have duplicated them, hugo is using your version instead of theme version.

https://github.com/javierasping/sentinel/tree/main/layouts

**Comment by javierasping** [comment]
I tried deleting my layouts folder locally and copying the one from the latest version of the theme, but I only have one language configured, it fails to run

javiercruces@HPOMEN15:~/Documentos/sentinel$ hugo server --disableFastRender --logLevel  info
Watching for changes in /home/javiercruces/Documentos/sentinel/{archetypes,assets,content,data,layouts,node_modules,package.hugo.json,package.json,static}
Watching for config changes in /home/javiercruces/Documentos/sentinel/config.yaml, /home/javiercruces/Documentos/sentinel/go.mod
Start building sites … 
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended linux/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio

INFO  copy static: syncing static files to /
INFO  build: running step process duration 60.831208ms
INFO  build: running step assemble duration 4.949826ms
ERROR render of "page" failed: "/home/javiercruces/Documentos/sentinel/layouts/notes/single.html:7:8": execute of template failed: template: notes/single.html:7:8: executing "sidebar" at <hugo>: can't evaluate field IsMultilingual in type interface {}
INFO  build: running step render duration 747.673214ms
INFO  build: running step postProcess duration 170.442µs
Built in 813 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/home/javiercruces/Documentos/sentinel/layouts/notes/single.html:7:8": execute of template failed: template: notes/single.html:7:8: executing "sidebar" at <hugo>: can't evaluate field IsMultilingual in type interface {}

**Comment by hossainemruz** [comment]
Update Hugo version to latest

**Comment by javierasping** [comment]
Thank you very much!!! By replacing the layouts folder with the latest one from the theme and updating Hugo, the issue has been resolved. 


One last thing !! On your example page, the text below the institution where you studied appears in white, but for me, it appears in black.

![image](https://github.com/hugo-toha/toha/assets/80594036/02d83a02-98a7-41f7-a0a0-278cd4e53858)

![image](https://github.com/hugo-toha/toha/assets/80594036/eb0979e7-09f3-45ef-b464-465eff6c2dc4)

**Comment by niltied** [comment]
@hossainemruz,

It's not possible for to share with you my repo. It's in my private self-hosted Gitlab. I build my website in Docker image with the last hugo version (0.126.2) and Toha 4.5.0. npm, tidy, every dependance is upgraded.

**Comment by hossainemruz** [comment]
> Thank you very much!!! By replacing the layouts folder with the latest one from the theme and updating Hugo, the issue has been resolved. 
> 
> 
> 
> 
> 
> One last thing !! On your example page, the text below the institution where you studied appears in white, but for me, it appears in black.
> 
> 
> 
> ![image](https://github.com/hugo-toha/toha/assets/80594036/02d83a02-98a7-41f7-a0a0-278cd4e53858)
> 
> 
> 
> ![image](https://github.com/hugo-toha/toha/assets/80594036/eb0979e7-09f3-45ef-b464-465eff6c2dc4)
> 
> 

The fix for the text issue is already in the main branch. I will release soon.

**Comment by hossainemruz** [comment]
> Thank you very much!!! By replacing the layouts folder with the latest one from the theme and updating Hugo, the issue has been resolved. 
> 
> 
> 
> 
> 
> One last thing !! On your example page, the text below the institution where you studied appears in white, but for me, it appears in black.
> 
> 
> 
> ![image](https://github.com/hugo-toha/toha/assets/80594036/02d83a02-98a7-41f7-a0a0-278cd4e53858)
> 
> 
> 
> ![image](https://github.com/hugo-toha/toha/assets/80594036/eb0979e7-09f3-45ef-b464-465eff6c2dc4)
> 
> 

Can you share the link to your site. Also, sharing packages.json may help to identify the issue.

**Comment by hossainemruz** [comment]
@niltied Can you share the link to your site. Also, sharing `packages.json` may help to identify the issue.

**Comment by javierasping** [comment]
Perfect, thank you very much!! As for me, you can close the issue; I'll keep an eye on the repository for the update. Do you know if the pipeline that updates the theme will add the change for me, or should I keep an eye out to do it manually?


My website --> www.javiercd.es

Link to package.json https://github.com/javierasping/sentinel/blob/main/package.json

```bash
{
  "comments": {
    "dependencies": {},
    "devDependencies": {
      "@fontsource/mulish": "github.com/hugo-toha/toha/v4",
      "@fortawesome/fontawesome-free": "github.com/hugo-toha/toha/v4",
      "autoprefixer": "github.com/hugo-toha/toha/v4",
      "bootstrap": "github.com/hugo-toha/toha/v4",
      "eslint": "github.com/hugo-toha/toha/v4",
      "eslint-config-prettier": "github.com/hugo-toha/toha/v4",
      "eslint-config-standard": "github.com/hugo-toha/toha/v4",
      "eslint-plugin-import": "github.com/hugo-toha/toha/v4",
      "eslint-plugin-n": "github.com/hugo-toha/toha/v4",
      "eslint-plugin-no-jquery": "github.com/hugo-toha/toha/v4",
      "eslint-plugin-promise": "github.com/hugo-toha/toha/v4",
      "feather-icons": "github.com/hugo-toha/toha/v4",
      "filterizr": "github.com/hugo-toha/toha/v4",
      "flag-icon-css": "github.com/hugo-toha/toha/v4",
      "fuse.js": "github.com/hugo-toha/toha/v4",
      "highlight.js": "github.com/hugo-toha/toha/v4",
      "imagesloaded": "github.com/hugo-toha/toha/v4",
      "include-media": "github.com/hugo-toha/toha/v4",
      "ityped": "github.com/hugo-toha/toha/v4",
      "katex": "github.com/hugo-toha/toha/v4",
      "mark.js": "github.com/hugo-toha/toha/v4",
      "mermaid": "github.com/hugo-toha/toha/v4",
      "plyr": "github.com/hugo-toha/toha/v4",
      "popper.js": "github.com/hugo-toha/toha/v4",
      "postcss": "github.com/hugo-toha/toha/v4",
      "postcss-cli": "github.com/hugo-toha/toha/v4"
    }
  },
  "dependencies": {},
  "devDependencies": {
    "@fontsource/mulish": "4.5.13",
    "@fortawesome/fontawesome-free": "^6.2.0",
    "autoprefixer": "^10.4.13",
    "bootstrap": "^5.3.3",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-no-jquery": "^2.7.0",
    "eslint-plugin-promise": "^6.1.1",
    "feather-icons": "^4.29.1",
    "filterizr": "^2.2.4",
    "flag-icon-css": "^4.1.7",
    "fuse.js": "^6.6.2",
    "highlight.js": "^11.6.0",
    "imagesloaded": "^5.0.0",
    "include-media": "^1.4.10",
    "ityped": "^1.0.3",
    "katex": "^0.16.10",
    "mark.js": "^8.11.1",
    "mermaid": "^9.2.1",
    "plyr": "^3.7.2",
    "popper.js": "^1.16.1",
    "postcss": "^8.4.31",
    "postcss-cli": "^8.3.1"
  },
  "name": "hugo-toha.github.io",
  "version": "0.1.0"
}
```

**Comment by hossainemruz** [comment]
> Perfect, thank you very much!! As for me, you can close the issue; I'll keep an eye on the repository for the update. Do you know if the pipeline that updates the theme will add the change for me, or should I keep an eye out to do it manually?
> 
> 
> 
> 
> 
> My website --> www.javiercd.es
> 
> 
> 
> Link to package.json https://github.com/javierasping/sentinel/blob/main/package.json
> 
> 
> 
> ```bash
> 
> {
> 
>   "comments": {
> 
>     "dependencies": {},
> 
>     "devDependencies": {
> 
>       "@fontsource/mulish": "github.com/hugo-toha/toha/v4",
> 
>       "@fortawesome/fontawesome-free": "github.com/hugo-toha/toha/v4",
> 
>       "autoprefixer": "github.com/hugo-toha/toha/v4",
> 
>       "bootstrap": "github.com/hugo-toha/toha/v4",
> 
>       "eslint": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-config-prettier": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-config-standard": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-plugin-import": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-plugin-n": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-plugin-no-jquery": "github.com/hugo-toha/toha/v4",
> 
>       "eslint-plugin-promise": "github.com/hugo-toha/toha/v4",
> 
>       "feather-icons": "github.com/hugo-toha/toha/v4",
> 
>       "filterizr": "github.com/hugo-toha/toha/v4",
> 
>       "flag-icon-css": "github.com/hugo-toha/toha/v4",
> 
>       "fuse.js": "github.com/hugo-toha/toha/v4",
> 
>       "highlight.js": "github.com/hugo-toha/toha/v4",
> 
>       "imagesloaded": "github.com/hugo-toha/toha/v4",
> 
>       "include-media": "github.com/hugo-toha/toha/v4",
> 
>       "ityped": "github.com/hugo-toha/toha/v4",
> 
>       "katex": "github.com/hugo-toha/toha/v4",
> 
>       "mark.js": "github.com/hugo-toha/toha/v4",
> 
>       "mermaid": "github.com/hugo-toha/toha/v4",
> 
>       "plyr": "github.com/hugo-toha/toha/v4",
> 
>       "popper.js": "github.com/hugo-toha/toha/v4",
> 
>       "postcss": "github.com/hugo-toha/toha/v4",
> 
>       "postcss-cli": "github.com/hugo-toha/toha/v4"
> 
>     }
> 
>   },
> 
>   "dependencies": {},
> 
>   "devDependencies": {
> 
>     "@fontsource/mulish": "4.5.13",
> 
>     "@fortawesome/fontawesome-free": "^6.2.0",
> 
>     "autoprefixer": "^10.4.13",
> 
>     "bootstrap": "^5.3.3",
> 
>     "eslint": "^8.31.0",
> 
>     "eslint-config-prettier": "^8.6.0",
> 
>     "eslint-config-standard": "^17.0.0",
> 
>     "eslint-plugin-import": "^2.26.0",
> 
>     "eslint-plugin-n": "^15.6.0",
> 
>     "eslint-plugin-no-jquery": "^2.7.0",
> 
>     "eslint-plugin-promise": "^6.1.1",
> 
>     "feather-icons": "^4.29.1",
> 
>     "filterizr": "^2.2.4",
> 
>     "flag-icon-css": "^4.1.7",
> 
>     "fuse.js": "^6.6.2",
> 
>     "highlight.js": "^11.6.0",
> 
>     "imagesloaded": "^5.0.0",
> 
>     "include-media": "^1.4.10",
> 
>     "ityped": "^1.0.3",
> 
>     "katex": "^0.16.10",
> 
>     "mark.js": "^8.11.1",
> 
>     "mermaid": "^9.2.1",
> 
>     "plyr": "^3.7.2",
> 
>     "popper.js": "^1.16.1",
> 
>     "postcss": "^8.4.31",
> 
>     "postcss-cli": "^8.3.1"
> 
>   },
> 
>   "name": "hugo-toha.github.io",
> 
>   "version": "0.1.0"
> 
> }
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I asked package.json from @niltied. Your one is already good.

**Comment by niltied** [comment]
Hi @hossainemruz,

Finally, It was always OK. My pipeline works fine. My website is clean.

**Comment by hossainemruz** [comment]
@niltied I can't reach http://hugo.dietlin.eu/en/.

**Comment by niltied** [comment]
@hossainemruz, try again, it work fine now.

**Comment by hossainemruz** [comment]
@niltied What exactly your issue right now? I can see your site is working fine. The theme selector and language selector seems to be working properly.

**Comment by niltied** [comment]
@hossainemruz, it's a long time...

So, yes, everything work fine. I had mentioned earlier that I also had the issue. But in reality, I was mistaken. My site has always worked perfectly fine. I misunderstood the original problem. I was a bit too quick. You can close the issue as far as I'm concerned.
