### ISSUE TITLE
Receiving errors when starting the server (can't evaluate field IsMultilingual in type interface {})

### ISSUE THREAD

**Issue by Razortide** [hugo-toha/toha#957]
Hello all,

most probably, the problem sits in front of this very computer, but unfortunately, I haven't found a solution yet and hopefully, you will be able to help me out here:

I just created a new hugo site and wanted to install the beautiful Toha theme.

So, as a first step, I forked the repo here: https://github.com/Razortide/toha_razortide

Here is the link to my blog repo: https://github.com/Razortide/marcs_blog

I followed the instruction here word by word: https://toha-guides.netlify.app/posts/getting-started/prepare-site/, using my blog repo when it came to this line: hugo mod init github.com/<your user name>/<your repo name>

Since this didn't worked the way I hoped, I applied the following template for my hugo.yaml: https://github.com/hugo-toha/hugo-toha.github.io/blob/main/hugo.yaml.

I then ran the commands below and it worked without error:
![image](https://github.com/user-attachments/assets/7662e496-c031-4b12-ad87-0b088fff449a)

When I start to run the server using hugo server -w I receive the following errors:
![image](https://github.com/user-attachments/assets/2bbfff00-0531-4a61-9f98-6072cbae281b)

The mentioned files exchange for each run, but they always refer to the lang-selector.html and throw:
"can't evaluate field IsMultilingual in type interface {}"

I am at a loss here. Can anybody give me an advice how to proceed? That would be very much appreciated.

Best regards,
Marc

**Comment by hossainemruz** [comment]
What is your Hugo version?

**Comment by Razortide** [comment]
Hello @hossainemruz it is 

hugo v0.123.7+extended
go version go1.22.2
npm version is 9.2.0

**Comment by hossainemruz** [comment]
I don't see your forked repo: https://github.com/Razortide/toha_razortide
Also, why did you forked it?

**Comment by hossainemruz** [comment]
The easiest way to deploy, is to fork this repo and update the data with your own.
https://github.com/hugo-toha/hugo-toha.github.io

**Comment by Razortide** [comment]
Hey  @hossainemruz, I deleted the old fork because it was leading me to nowhere.
I now took the repo you directed me to, forked it to marc-toha.github.io and followed the instructions word by word (using hugo.yaml instead of config.yaml for obvious reasons), but I still ended up with the same error.

**Comment by hossainemruz** [comment]
Can you please try updating Hugo version?

**Comment by Razortide** [comment]
Hello @hossainemruz,

I updated to v0.131.0 extended and that did the trick. Thank you for your help. Based on the documentation it should have worked, right?

**Comment by hossainemruz** [comment]
> Based on the documentation it should have worked, right?

Yes. We should update the minimum Hugo version.
