### ISSUE TITLE
.Sites.First was deprecated in Hugo v0.127.0

### ISSUE THREAD

**Issue by FunctionalHacker** [hugo-toha/toha#959]
I get this warning on the latest version on newer versions of Hugo.
![image](https://github.com/user-attachments/assets/3137221e-91dc-47dd-a9e8-4fd0f85b3038)

Quick search in the codebase points to this as the culprit: https://github.com/hugo-toha/toha/blob/dde735d3af215e6143ac08f0b1123ac9d0d3602d/layouts/partials/navigators/lang-selector.html#L15

**Comment by hossainemruz** [comment]
Thank you for reporting it. I will take a look.
