### ISSUE TITLE
deprecated Node.js when updating the toha website

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#966]
Hi Toha team,

I recently updated my website, but then GitHub Actions threw the following error messages:
"The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, peaceiris/actions-hugo@v2.6.0, actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/"

You can find the full source here:
https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/10658418253

Could you please help me with this?
@hossainemruz

**Comment by hossainemruz** [comment]
Thank you @IhnwhiHeo for reporting. We will update the Node version.

**Comment by deining** [comment]
As seen [here](https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/10658418253), deployment of your site fails with latest hugo version 0.133.1.
The reason however is the use of an outdate theme version, not the use of deprecated Node.js versions.
I authored a [PR](https://github.com/IhnwhiHeo/ihnwhiheo.github.io/pull/122) that resolves your issues.

**Comment by IhnwhiHeo** [comment]
Thank you so much @hossainemruz and @deining for your quick help! I really appreciate it!
