### ISSUE TITLE
CSS are not getting applied properly in list page layout

### ISSUE THREAD

**Issue by javierasping** [hugo-toha/toha#968]
it seems that after updating to the latest version of Hugo 134.0 - 134.1, the post section is being generated incorrectly. I'll attach some images below:

![image](https://github.com/user-attachments/assets/a6cf6fae-5ab6-42a9-9003-feaa58fc40db)

I noticed this bug when I accessed my page in production, it didn't happen locally. This occurred after I updated to the latest version of Hugo, from 134.0 to 134.1.

This didn't happen with previous versions of Hugo.

[Bug](https://www.javiercd.es/posts/# )

Additionally, in the posts, the brief description that is now shown is larger, including content from the actual post. In some cases, the entire post is in the description.

![image](https://github.com/user-attachments/assets/dc295f53-cb40-4f51-816f-0d3d0f5221f5)

**Comment by javierasping** [comment]
Mi repo si https://github.com/javierasping/sentinel

**Comment by hossainemruz** [comment]
I have noticed the same issue. Working on the fix.

**Comment by hossainemruz** [comment]
Look like the issue is in Hugo version but not in the theme.

**Comment by hossainemruz** [comment]
Actually, Hugo introduced a breaking change for `.Summary` behavior in `v0.134.0`. This PR should fix the issue.
https://github.com/hugo-toha/toha/pull/969
